#!/usr/bin/bash

#_                   _ _ _  _ _____ _  _
#| | _______   ____ _| | | || |___  | || |
#| |/ / _ \ \ / / _` | | | || |_ / /| || |_
#|   <  __/\ V / (_| | | |__   _/ / |__   _|
#|_|\_\___| \_/ \__,_|_|_|  |_|/_/     |_|

strip_down(){
  # # Security options
  # plain ""
  # msg2 "Enable Security options"
  # # Security
  # scripts/config --enable CONFIG_SECURITY_DMESG_RESTRICT
  # scripts/config --enable CONFIG_SECURITY
  # scripts/config --enable CONFIG_SECURITY_WRITABLE_HOOKS
  # scripts/config --enable CONFIG_SECURITYFS
  # scripts/config --enable CONFIG_SECURITY_NETWORK
  # scripts/config --enable CONFIG_PAGE_TABLE_ISOLATION
  # scripts/config --enable CONFIG_SECURITY_INFINIBAND
  # scripts/config --enable CONFIG_SECURITY_NETWORK_XFRM
  # scripts/config --enable CONFIG_SECURITY_PATH
  # scripts/config --enable CONFIG_INTEL_TXT
  # scripts/config --set-val CONFIG_LSM_MMAP_MIN_ADDR 65536
  # scripts/config --enable CONFIG_HAVE_HARDENED_USERCOPY_ALLOCATOR
  # scripts/config --enable CONFIG_HARDENED_USERCOPY
  # scripts/config --enable CONFIG_HARDENED_USERCOPY_FALLBACK
  # scripts/config --enable CONFIG_HARDENED_USERCOPY_PAGESPAN
  # scripts/config --enable CONFIG_FORTIFY_SOURCE
  # scripts/config --enable CONFIG_STATIC_USERMODEHELPER
  # scripts/config --enable CONFIG_STATIC_USERMODEHELPER_PATH
  # scripts/config --set-val CONFIG_LSM "lockdown,yama,bpf"
  # # Safesetid
  # scripts/config --enable CONFIG_SECURITY_SAFESETID
  # # Selinux
  # scripts/config --enable CONFIG_SECURITY_SELINUX
  # scripts/config --enable CONFIG_SECURITY_SELINUX_BOOTPARAM
  # scripts/config --disable CONFIG_SECURITY_SELINUX_DISABLE
  # scripts/config --enable CONFIG_SECURITY_SELINUX_DEVELOP
  # scripts/config --enable CONFIG_SECURITY_SELINUX_AVC_STATS
  # scripts/config --set-val CONFIG_SECURITY_SELINUX_CHECKREQPROT_VALUE 0
  # scripts/config --set-val CONFIG_SECURITY_SELINUX_SIDTAB_HASH_BITS 13
  # scripts/config --set-val CONFIG_SECURITY_SELINUX_SID2STR_CACHE_SIZE 256
  # # Smack
  # scripts/config --enable CONFIG_SECURITY_SMACK
  # scripts/config --enable CONFIG_SECURITY_SMACK_BRINGUP
  # scripts/config --enable CONFIG_SECURITY_SMACK_NETFILTER
  # scripts/config --enable CONFIG_SECURITY_SMACK_APPEND_SIGNALS
  # # Tomoyo
  # scripts/config --enable CONFIG_SECURITY_TOMOYO
  # scripts/config --set-val CONFIG_SECURITY_TOMOYO_MAX_ACCEPT_ENTRY 2048
  # scripts/config --set-val CONFIG_SECURITY_TOMOYO_MAX_AUDIT_LOG 1024
  # scripts/config --enable CONFIG_SECURITY_TOMOYO_OMIT_USERSPACE_LOADER
  # scripts/config --set-str CONFIG_SECURITY_TOMOYO_POLICY_LOADER "/sbin/tomoyo-init"
  # scripts/config --set-str CONFIG_SECURITY_TOMOYO_ACTIVATION_TRIGGER "/sbin/init"
  # scripts/config --disable CONFIG_SECURITY_TOMOYO_INSECURE_BUILTIN_SETTING
  # # Apparmor
  # scripts/config --enable CONFIG_SECURITY_APPARMOR
  # scripts/config --enable CONFIG_SECURITY_APPARMOR_HASH
  # scripts/config --enable CONFIG_SECURITY_APPARMOR_HASH_DEFAULT
  # # Yama
  # scripts/config --enable CONFIG_SECURITY_YAMA
  #
  # sleep 2s
  #
  # # Library routines
  # msg2 "Enable Library routines (CONFIG_FONT_TER16x32)"
  # scripts/config --enable CONFIG_FONT_TER16x32
  #
  # sleep 2s
  #
  # # Kernel hacking -> Compile-time checks and compiler options -> Make section mismatch errors non-fatal
  # msg2 "Enable CONFIG_SECTION_MISMATCH_WARN_ONLY"
  # scripts/config --enable CONFIG_SECTION_MISMATCH_WARN_ONLY
  #
  # sleep 2s

  plain ""

############ Accessibility ############

  # Disable accessibility
  msg2 "Disable accessibility"
  scripts/config --disable CONFIG_ACCESSIBILITY
  # Disable braille
  echo "Disable braille"
  scripts/config --disable CONFIG_A11Y_BRAILLE_CONSOLE
  # Disable screen reader
  echo "Disable screen reader"
  scripts/config --disable CONFIG_SPEAKUP
  scripts/config --disable CONFIG_SPEAKUP_SERIALIO
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_ACNTSA
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_ACNTPC
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_APOLLO
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_AUDPTR
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_BNS
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_DECTLK
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_DECEXT
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_DECPC
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_DTLK
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_KEYPC
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_LTLK
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_SOFT
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_SPKOUT
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_TXPRT
  scripts/config --disable CONFIG_SPEAKUP_SYNTH_DUMMY

#######################################

  sleep 2s

############ Drivers/gpu/drm ############

  # Add full support for DRM
  msg2 "Add full support for DRM"
  scripts/config --module CONFIG_DRM
  scripts/config --module CONFIG_DRM_MIPI_DBI
  scripts/config --enable CONFIG_DRM_MIPI_DSI
  scripts/config --enable CONFIG_DRM_DP_AUX_CHARDEV
  scripts/config --enable CONFIG_DRM_KMS_HELPER
  scripts/config --enable CONFIG_DRM_KMS_FB_HELPER
  scripts/config --enable CONFIG_DRM_FBDEV_EMULATION
  scripts/config --set-val CONFIG_DRM_FBDEV_OVERALLOC 100
  scripts/config --enable CONFIG_DRM_FBDEV_LEAK_PHYS_SMEM
  scripts/config --enable CONFIG_DRM_LOAD_EDID_FIRMWARE
  scripts/config --enable CONFIG_DRM_DP_CEC
  scripts/config --module CONFIG_DRM_TTM
  scripts/config --module CONFIG_DRM_VRAM_HELPER
  scripts/config --module CONFIG_DRM_TTM_HELPER
  scripts/config --enable CONFIG_DRM_GEM_CMA_HELPER
  scripts/config --enable CONFIG_DRM_KMS_CMA_HELPER
  scripts/config --enable CONFIG_DRM_GEM_SHMEM_HELPER
  scripts/config --enable CONFIG_DRM_VM
  scripts/config --module CONFIG_DRM_SCHED
  scripts/config --module CONFIG_DRM_RADEON
  scripts/config --module CONFIG_DRM_AMDGPU
  scripts/config --module CONFIG_DRM_VGEM
  scripts/config --module CONFIG_DRM_VKMS
  scripts/config --enable CONFIG_DRM_LEGACY
  scripts/config --module CONFIG_DRM_TDFX
  scripts/config --module CONFIG_DRM_R128
  scripts/config --module CONFIG_DRM_I810
  scripts/config --module CONFIG_DRM_MGA
  scripts/config --module CONFIG_DRM_SIS
  scripts/config --module CONFIG_DRM_VIA
  scripts/config --module CONFIG_DRM_SAVAGE
  scripts/config --enable CONFIG_DRM_EXPORT_FOR_TESTS
  scripts/config --enable CONFIG_DRM_PANEL_ORIENTATION_QUIRKS
  scripts/config --enable CONFIG_DRM_LIB_RANDOM
  scripts/config --enable CONFIG_DRM_DEBUG_MM
  scripts/config --enable CONFIG_DRM_DEBUG_SELFTEST
  scripts/config --enable CONFIG_DRM_DEBUG_DP_MST_TOPOLOGY_REFS

  sleep 2s

  # Disable uneeded gpu drivers
  msg2 "Disable uneeded gpu drivers"
  # Arc
  echo "Disable Arc drivers"
  scripts/config --disable CONFIG_DRM_ARCPGU
  # Arm
  echo "Disable Arm drivers"
  scripts/config --disable CONFIG_DRM_HDLCD
  scripts/config --disable CONFIG_DRM_HDLCD_SHOW_UNDERRUN
  scripts/config --disable CONFIG_DRM_MALI_DISPLAY
  scripts/config --disable CONFIG_DRM_KOMEDA
  # Armada
  echo "Disable Armada drivers"
  scripts/config --disable CONFIG_DRM_ARMADA
  # Aspeed
  echo "Disable Aspeed drivers"
  scripts/config --disable CONFIG_DRM_ASPEED_GFX
  # Ast
  echo "Disable Ast drivers"
  scripts/config --disable CONFIG_DRM_AST
  # Atmel-hlcdc
  echo "Disable Atmel-hlcdc drivers"
  scripts/config --disable CONFIG_DRM_ATMEL_HLCDC
  # Bochs
  echo "Disable Bochs drivers"
  scripts/config --disable CONFIG_DRM_BOCHS
  # Bridge
  echo "Disable Bridge drivers"
  scripts/config --disable CONFIG_DRM_CDNS_DSI
  scripts/config --disable CONFIG_DRM_CHRONTEL_CH7033
  scripts/config --disable CONFIG_DRM_DISPLAY_CONNECTOR
  scripts/config --disable CONFIG_DRM_LONTIUM_LT9611
  scripts/config --disable CONFIG_DRM_LONTIUM_LT9611UXC
  scripts/config --disable CONFIG_DRM_LVDS_CODEC
  scripts/config --disable CONFIG_DRM_MEGACHIPS_STDPXXXX_GE_B850V3_FW
  scripts/config --disable CONFIG_DRM_NWL_MIPI_DSI
  scripts/config --disable CONFIG_DRM_NXP_PTN3460
  scripts/config --disable CONFIG_DRM_PARADE_PS8622
  scripts/config --disable CONFIG_DRM_PARADE_PS8640
  scripts/config --disable CONFIG_DRM_SIL_SII8620
  scripts/config --disable CONFIG_DRM_SII902X
  scripts/config --disable CONFIG_DRM_SII9234
  scripts/config --disable CONFIG_DRM_SIMPLE_BRIDGE
  scripts/config --disable CONFIG_DRM_THINE_THC63LVD1024
  scripts/config --disable CONFIG_DRM_TOSHIBA_TC358762
  scripts/config --disable CONFIG_DRM_TOSHIBA_TC358764
  scripts/config --disable CONFIG_DRM_TOSHIBA_TC358767
  scripts/config --disable CONFIG_DRM_TOSHIBA_TC358768
  scripts/config --disable CONFIG_DRM_TOSHIBA_TC358775
  scripts/config --disable CONFIG_DRM_TI_TFP410
  scripts/config --disable CONFIG_DRM_TI_SN65DSI86
  scripts/config --disable CONFIG_DRM_TI_TPD12S015
  # Bridge/ADV
  echo "Disable Bridge/Adv drivers"
  scripts/config --disable CONFIG_DRM_I2C_ADV7511
  scripts/config --disable CONFIG_DRM_I2C_ADV7511_AUDIO
  scripts/config --disable CONFIG_DRM_I2C_ADV7511_CEC
  # Bridge/Analogix
  echo "Disable Bridge/Analogix drivers"
  scripts/config --disable CONFIG_DRM_ANALOGIX_ANX6345
  scripts/config --disable CONFIG_DRM_ANALOGIX_ANX78XX
  scripts/config --disable CONFIG_DRM_ANALOGIX_DP
  scripts/config --disable CONFIG_DRM_ANALOGIX_ANX7625
  # Bridge/Synopsys
  echo "Disable Bridge/Synopsys drivers"
  scripts/config --disable CONFIG_DRM_DW_HDMI
  scripts/config --disable CONFIG_DRM_DW_HDMI_AHB_AUDIO
  scripts/config --disable CONFIG_DRM_DW_HDMI_I2S_AUDIO
  scripts/config --disable CONFIG_DRM_DW_HDMI_CEC
  scripts/config --disable CONFIG_DRM_DW_MIPI_DSI
  # Etnaviv
  echo "Disable Etnaviv drivers"
  scripts/config --disable CONFIG_DRM_ETNAVIV
  scripts/config --disable CONFIG_DRM_ETNAVIV_THERMAL
  # Exynos
  echo "Disable Exynos drivers"
  scripts/config --disable CONFIG_DRM_EXYNOS
  scripts/config --disable CONFIG_DRM_EXYNOS_FIMD
  scripts/config --disable CONFIG_DRM_EXYNOS5433_DECON
  scripts/config --disable CONFIG_DRM_EXYNOS7_DECON
  scripts/config --disable CONFIG_DRM_EXYNOS_MIXER
  scripts/config --disable CONFIG_DRM_EXYNOS_VIDI
  scripts/config --disable CONFIG_DRM_EXYNOS_DPI
  scripts/config --disable CONFIG_DRM_EXYNOS_DSI
  scripts/config --disable CONFIG_DRM_EXYNOS_DP
  scripts/config --disable CONFIG_DRM_EXYNOS_HDMI
  scripts/config --disable CONFIG_DRM_EXYNOS_MIC
  scripts/config --disable CONFIG_DRM_EXYNOS_G2D
  scripts/config --disable CONFIG_DRM_EXYNOS_IPP
  scripts/config --disable CONFIG_DRM_EXYNOS_FIMC
  scripts/config --disable CONFIG_DRM_EXYNOS_ROTATOR
  scripts/config --disable CONFIG_DRM_EXYNOS_SCALER
  scripts/config --disable CONFIG_DRM_EXYNOS_GSC
  # Fsl-dcu
  echo "Disable Fsl-dcu drivers"
  scripts/config --disable CONFIG_DRM_FSL_DCU
  # Hisilicon
  echo "Disable Hisilicon drivers"
  scripts/config --disable CONFIG_DRM_HISI_HIBMC
  scripts/config --disable CONFIG_DRM_HISI_KIRIN
  # I2c
  echo "Disable I2c drivers"
  scripts/config --disable CONFIG_DRM_I2C_CH7006
  scripts/config --disable CONFIG_DRM_I2C_SIL164
  scripts/config --disable CONFIG_DRM_I2C_NXP_TDA998X
  scripts/config --disable CONFIG_DRM_I2C_NXP_TDA9950
  # IMX
  echo "Disable Imx drivers"
  scripts/config --disable CONFIG_DRM_IMX_DCSS
  scripts/config --disable CONFIG_DRM_IMX
  scripts/config --disable CONFIG_DRM_IMX_PARALLEL_DISPLAY
  scripts/config --disable CONFIG_DRM_IMX_TVE
  scripts/config --disable CONFIG_DRM_IMX_LDB
  scripts/config --disable CONFIG_DRM_IMX_HDMI
  # Ingenic
  echo "Disable Ingenic drivers"
  scripts/config --disable CONFIG_DRM_INGENIC
  scripts/config --disable CONFIG_DRM_INGENIC_IPU
  # Kmb
  echo "Disable Kmb drivers"
  scripts/config --disable CONFIG_DRM_KMB_DISPLAY
  # Lima
  echo "Disable Lima drivers"
  scripts/config --disable CONFIG_DRM_LIMA
  # MCDE
  echo "Disable Mcda drivers"
  scripts/config --disable CONFIG_DRM_MCDE
  # Mediatek
  echo "Disable Mediatek drivers"
  scripts/config --disable CONFIG_DRM_MEDIATEK
  scripts/config --disable CONFIG_DRM_MEDIATEK_HDMI
  # Meson
  echo "Disable Meson drivers"
  scripts/config --disable CONFIG_DRM_MESON
  scripts/config --disable CONFIG_DRM_MESON_DW_HDMI
  # Mgag200
  echo "Disable Mgag200 drivers"
  scripts/config --disable CONFIG_DRM_MGAG200
  # Msm
  echo "Disable Msm drivers"
  scripts/config --disable CONFIG_DRM_MSM
  scripts/config --disable CONFIG_DRM_MSM_GPU_STATE
  scripts/config --disable CONFIG_DRM_MSM_REGISTER_LOGGING
  scripts/config --disable CONFIG_DRM_MSM_GPU_SUDO
  scripts/config --disable CONFIG_DRM_MSM_HDMI_HDCP
  scripts/config --disable CONFIG_DRM_MSM_DP
  scripts/config --disable CONFIG_DRM_MSM_DSI
  scripts/config --disable CONFIG_DRM_MSM_DSI_PLL
  scripts/config --disable CONFIG_DRM_MSM_DSI_28NM_PHY
  scripts/config --disable CONFIG_DRM_MSM_DSI_20NM_PHY
  scripts/config --disable CONFIG_DRM_MSM_DSI_28NM_8960_PHY
  scripts/config --disable CONFIG_DRM_MSM_DSI_14NM_PHY
  scripts/config --disable CONFIG_DRM_MSM_DSI_10NM_PHY
  scripts/config --disable CONFIG_DRM_MSM_DSI_7NM_PHY
  # MXSFB
  echo "Disable MXSFB drivers"
  scripts/config --disable CONFIG_DRM_MXS
  scripts/config --disable CONFIG_DRM_MXSFB
  # Omapdrm
  echo "Disable Omapdrm drivers"
  scripts/config --disable CONFIG_DRM_OMAP
  scripts/config --disable CONFIG_DRM_OMAP_PANEL_DSI_CM
  scripts/config --disable CONFIG_OMAP2_DSS_INIT
  scripts/config --disable CONFIG_OMAP_DSS_BASE
  scripts/config --disable CONFIG_OMAP2_DSS
  scripts/config --disable CONFIG_OMAP2_DSS_DEBUG
  scripts/config --disable CONFIG_OMAP2_DSS_DEBUGFS
  scripts/config --disable CONFIG_OMAP2_DSS_COLLECT_IRQ_STATS
  scripts/config --disable CONFIG_OMAP2_DSS_DPI
  scripts/config --disable CONFIG_OMAP2_DSS_VENC
  scripts/config --disable CONFIG_OMAP2_DSS_HDMI_COMMON
  scripts/config --disable CONFIG_OMAP4_DSS_HDMI
  scripts/config --disable CONFIG_OMAP4_DSS_HDMI_CEC
  scripts/config --disable CONFIG_OMAP5_DSS_HDMI
  scripts/config --disable CONFIG_OMAP2_DSS_SDI
  scripts/config --disable CONFIG_OMAP2_DSS_DSI
  scripts/config --disable CONFIG_OMAP2_DSS_MIN_FCK_PER_PCK
  scripts/config --disable CONFIG_OMAP2_DSS_SLEEP_AFTER_VENC_RESET
  # Panfrost
  echo "Disable Panfrost drivers"
  scripts/config --disable CONFIG_DRM_PANFROST
  # Panel
  echo "Disable Panel drivers"
  scripts/config --disable CONFIG_DRM_PANEL
  scripts/config --disable CONFIG_DRM_PANEL_ABT_Y030XX067A
  scripts/config --disable CONFIG_DRM_PANEL_ARM_VERSATILE
  scripts/config --disable CONFIG_DRM_PANEL_ASUS_Z00T_TM5P5_NT35596
  scripts/config --disable CONFIG_DRM_PANEL_BOE_HIMAX8279D
  scripts/config --disable CONFIG_DRM_PANEL_BOE_TV101WUM_NL6
  scripts/config --disable CONFIG_DRM_PANEL_LVDS
  scripts/config --disable CONFIG_DRM_PANEL_SIMPLE
  scripts/config --disable CONFIG_DRM_PANEL_ELIDA_KD35T133
  scripts/config --disable CONFIG_DRM_PANEL_FEIXIN_K101_IM2BA02
  scripts/config --disable CONFIG_DRM_PANEL_FEIYANG_FY07024DI26A30D
  scripts/config --disable CONFIG_DRM_PANEL_ILITEK_IL9322
  scripts/config --disable CONFIG_DRM_PANEL_ILITEK_ILI9881C
  scripts/config --disable CONFIG_DRM_PANEL_INNOLUX_P079ZCA
  scripts/config --disable CONFIG_DRM_PANEL_JDI_LT070ME05000
  scripts/config --disable CONFIG_DRM_PANEL_KINGDISPLAY_KD097D04
  scripts/config --disable CONFIG_DRM_PANEL_LEADTEK_LTK050H3146W
  scripts/config --disable CONFIG_DRM_PANEL_LEADTEK_LTK500HD1829
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_LD9040
  scripts/config --disable CONFIG_DRM_PANEL_LG_LB035Q02
  scripts/config --disable CONFIG_DRM_PANEL_LG_LG4573
  scripts/config --disable CONFIG_DRM_PANEL_NEC_NL8048HL11
  scripts/config --disable CONFIG_DRM_PANEL_NOVATEK_NT35510
  scripts/config --disable CONFIG_DRM_PANEL_NOVATEK_NT36672A
  scripts/config --disable CONFIG_DRM_PANEL_NOVATEK_NT39016
  scripts/config --disable CONFIG_DRM_PANEL_MANTIX_MLAF057WE51
  scripts/config --disable CONFIG_DRM_PANEL_OLIMEX_LCD_OLINUXINO
  scripts/config --disable CONFIG_DRM_PANEL_ORISETECH_OTM8009A
  scripts/config --disable CONFIG_DRM_PANEL_OSD_OSD101T2587_53TS
  scripts/config --disable CONFIG_DRM_PANEL_PANASONIC_VVX10F034N00
  scripts/config --disable CONFIG_DRM_PANEL_RASPBERRYPI_TOUCHSCREEN
  scripts/config --disable CONFIG_DRM_PANEL_RAYDIUM_RM67191
  scripts/config --disable CONFIG_DRM_PANEL_RAYDIUM_RM68200
  scripts/config --disable CONFIG_DRM_PANEL_RONBO_RB070D30
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_S6D16D0
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_S6E3HA2
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_S6E63J0X03
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_S6E63M0
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_S6E63M0_SPI
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_S6E63M0_DSI
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_S6E88A0_AMS452EF01
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_S6E8AA0
  scripts/config --disable CONFIG_DRM_PANEL_SAMSUNG_SOFEF00
  scripts/config --disable CONFIG_DRM_PANEL_SEIKO_43WVF1G
  scripts/config --disable CONFIG_DRM_PANEL_SHARP_LQ101R1SX01
  scripts/config --disable CONFIG_DRM_PANEL_SHARP_LS037V7DW01
  scripts/config --disable CONFIG_DRM_PANEL_SHARP_LS043T1LE01
  scripts/config --disable CONFIG_DRM_PANEL_SITRONIX_ST7701
  scripts/config --disable CONFIG_DRM_PANEL_SITRONIX_ST7703
  scripts/config --disable CONFIG_DRM_PANEL_SITRONIX_ST7789V
  scripts/config --disable CONFIG_DRM_PANEL_SONY_ACX424AKP
  scripts/config --disable CONFIG_DRM_PANEL_SONY_ACX565AKM
  scripts/config --disable CONFIG_DRM_PANEL_TDO_TL070WSH30
  scripts/config --disable CONFIG_DRM_PANEL_TPO_TD028TTEC1
  scripts/config --disable CONFIG_DRM_PANEL_TPO_TD043MTEA1
  scripts/config --disable CONFIG_DRM_PANEL_TPO_TPG110
  scripts/config --disable CONFIG_DRM_PANEL_TRULY_NT35597_WQXGA
  scripts/config --disable CONFIG_DRM_PANEL_VISIONOX_RM69299
  scripts/config --disable CONFIG_DRM_PANEL_XINPENG_XPP055C272
  # PL111
  echo "Disable PL111 drivers"
  scripts/config --disable CONFIG_DRM_PL111
  # Qxl
  echo "Disable Qxl drivers"
  scripts/config --disable CONFIG_DRM_QXL
  # Rcar-du
  echo "Disable Rcar-du drivers"
  scripts/config --disable CONFIG_DRM_RCAR_DU
  scripts/config --disable CONFIG_DRM_RCAR_CMM
  scripts/config --disable CONFIG_DRM_RCAR_DW_HDMI
  scripts/config --disable CONFIG_DRM_RCAR_LVDS
  scripts/config --disable CONFIG_DRM_RCAR_VSP
  scripts/config --disable CONFIG_DRM_RCAR_WRITEBACK
  # Rockchip
  echo "Disable Rockchip drivers"
  scripts/config --disable CONFIG_DRM_ROCKCHIP
  scripts/config --disable CONFIG_ROCKCHIP_ANALOGIX_DP
  scripts/config --disable CONFIG_ROCKCHIP_CDN_DP
  scripts/config --disable CONFIG_ROCKCHIP_DW_HDMI
  scripts/config --disable CONFIG_ROCKCHIP_DW_MIPI_DSI
  scripts/config --disable CONFIG_ROCKCHIP_INNO_HDMI
  scripts/config --disable CONFIG_ROCKCHIP_LVDS
  scripts/config --disable CONFIG_ROCKCHIP_RGB
  scripts/config --disable CONFIG_ROCKCHIP_RK3066_HDMI
  # SH Mobile
  echo "Disable SH Mobile drivers"
  scripts/config --disable CONFIG_DRM_SHMOBILE
  # Sti
  echo "Disable Sti drivers"
  scripts/config --disable CONFIG_DRM_STI
  # Stm
  echo "Disable Stm drivers"
  scripts/config --disable CONFIG_DRM_STM
  scripts/config --disable CONFIG_DRM_STM_DSI
  # Sun4I
  echo "Disable Sun4I drivers"
  scripts/config --disable CONFIG_DRM_SUN4I
  scripts/config --disable CONFIG_DRM_SUN4I_HDMI
  scripts/config --disable CONFIG_DRM_SUN4I_HDMI_CEC
  scripts/config --disable CONFIG_DRM_SUN4I_BACKEND
  scripts/config --disable CONFIG_DRM_SUN6I_DSI
  scripts/config --disable CONFIG_DRM_SUN8I_DW_HDMI
  scripts/config --disable CONFIG_DRM_SUN8I_MIXER
  scripts/config --disable CONFIG_DRM_SUN8I_TCON_TOP
  # Tegra
  echo "Disable Tegra drivers"
  scripts/config --disable CONFIG_DRM_TEGRA
  scripts/config --disable CONFIG_DRM_TEGRA_DEBUG
  scripts/config --disable CONFIG_DRM_TEGRA_STAGING
  # Tidss
  echo "Disable Tidss drivers"
  scripts/config --disable CONFIG_DRM_TIDSS
  # Tilcdc
  echo "Disable Tilcdc drivers"
  scripts/config --disable CONFIG_DRM_TILCDC
  # Tiny
  echo "Disable Tiny drivers"
  scripts/config --disable CONFIG_DRM_CIRRUS_QEMU
  scripts/config --disable CONFIG_DRM_GM12U320
  scripts/config --disable CONFIG_TINYDRM_HX8357D
  scripts/config --disable CONFIG_TINYDRM_ILI9225
  scripts/config --disable CONFIG_TINYDRM_ILI9341
  scripts/config --disable CONFIG_TINYDRM_ILI9486
  scripts/config --disable CONFIG_TINYDRM_MI0283QT
  scripts/config --disable CONFIG_TINYDRM_REPAPER
  scripts/config --disable CONFIG_TINYDRM_ST7586
  scripts/config --disable CONFIG_TINYDRM_ST7735R
  # Tve200
  echo "Disable Tve200 drivers"
  scripts/config --disable CONFIG_DRM_TVE200
  # Udl
  echo "Disable Udl drivers"
  scripts/config --disable CONFIG_DRM_UDL
  # V3d
  echo "Disable V3d drivers"
  scripts/config --disable CONFIG_DRM_V3D
  # Vc4
  echo "Disable Vc4 drivers"
  scripts/config --disable CONFIG_DRM_VC4
  scripts/config --disable CONFIG_DRM_VC4_HDMI_CEC
  # Xlnx
  echo "Disable Xlnx drivers"
  scripts/config --disable CONFIG_DRM_ZYNQMP_DPSUB
  # Zte
  echo "Disable Zte drivers"
  scripts/config --disable CONFIG_DRM_ZTE

  sleep 2s

  # Enable CONFIG_DRM_BRIDGE/CONFIG_DRM_PANEL_BRIDGE
  msg2 "Enable CONFIG_DRM_BRIDGE/CONFIG_DRM_PANEL_BRIDGE"
  scripts/config --enable CONFIG_DRM_BRIDGE
  scripts/config --enable CONFIG_DRM_PANEL_BRIDGE

  sleep 2s

  # Add full support for amd/intel/nouveau gpu
  msg2 "Add full support for amd/intel/nouveau gpu"
  # AMD
  echo "Enable full support for AMD GPU"
  scripts/config --enable CONFIG_DRM_AMD_ACP
  scripts/config --enable CONFIG_DRM_AMDGPU_SI
  scripts/config --enable CONFIG_DRM_AMDGPU_CIK
  scripts/config --enable CONFIG_DRM_AMDGPU_USERPTR
  scripts/config --enable CONFIG_DRM_AMDGPU_GART_DEBUGFS
  scripts/config --enable CONFIG_HSA_AMD
  scripts/config --enable CONFIG_DRM_AMD_DC
  scripts/config --enable CONFIG_DRM_AMD_DC_DCN
  scripts/config --enable CONFIG_DRM_AMD_DC_HDCP
  scripts/config --enable CONFIG_DRM_AMD_DC_SI
  scripts/config --enable CONFIG_DEBUG_KERNEL_DC
  scripts/config --enable CONFIG_DRM_RADEON_USERPTR
  # Intel
  echo "Enable full support for Intel GPU"
  scripts/config --module CONFIG_DRM_I915
  scripts/config --set-val CONFIG_DRM_I915_FORCE_PROBE "*"
  scripts/config --enable CONFIG_DRM_I915_CAPTURE_ERROR
  scripts/config --enable CONFIG_DRM_I915_COMPRESS_ERROR
  scripts/config --enable CONFIG_DRM_I915_USERPTR
  scripts/config --enable CONFIG_DRM_I915_GVT
  scripts/config --enable CONFIG_DRM_I915_GVT_KVMGT
  scripts/config --enable CONFIG_DRM_I915_WERROR
  scripts/config --enable CONFIG_DRM_I915_DEBUG
  scripts/config --enable CONFIG_DRM_I915_DEBUG_MMIO
  scripts/config --enable CONFIG_DRM_I915_DEBUG_GEM
  scripts/config --enable CONFIG_DRM_I915_ERRLOG_GEM
  scripts/config --enable CONFIG_DRM_I915_TRACE_GEM
  scripts/config --enable CONFIG_DRM_I915_TRACE_GTT
  scripts/config --enable CONFIG_DRM_I915_SW_FENCE_DEBUG_OBJECTS
  scripts/config --enable CONFIG_DRM_I915_SW_FENCE_CHECK_DAG
  scripts/config --enable CONFIG_DRM_I915_DEBUG_GUC
  scripts/config --enable CONFIG_DRM_I915_SELFTEST
  scripts/config --enable CONFIG_DRM_I915_SELFTEST_BROKEN
  scripts/config --enable CONFIG_DRM_I915_LOW_LEVEL_TRACEPOINTS
  scripts/config --enable CONFIG_DRM_I915_DEBUG_VBLANK_EVADE
  scripts/config --enable CONFIG_DRM_I915_DEBUG_RUNTIME_PM
  scripts/config --set-val CONFIG_DRM_I915_FENCE_TIMEOUT 10000
  scripts/config --set-val CONFIG_DRM_I915_USERFAULT_AUTOSUSPEND 250
  scripts/config --set-val CONFIG_DRM_I915_HEARTBEAT_INTERVAL 2500
  scripts/config --set-val CONFIG_DRM_I915_PREEMPT_TIMEOUT 640
  scripts/config --set-val CONFIG_DRM_I915_MAX_REQUEST_BUSYWAIT 8000
  scripts/config --set-val CONFIG_DRM_I915_STOP_TIMEOUT 100
  scripts/config --set-val CONFIG_DRM_I915_TIMESLICE_DURATION 1
  scripts/config --enable CONFIG_DRM_I915_UNSTABLE
  scripts/config --enable CONFIG_DRM_I915_UNSTABLE_FAKE_LMEM
  # Intel/GMA500
  scripts/config --enable CONFIG_DRM_GMA500
  scripts/config --enable CONFIG_DRM_GMA600
  scripts/config --enable CONFIG_DRM_GMA3600
  scripts/config --enable CONFIG_DRM_MEDFIELD
  # Nouveau
  echo "Enable full support for Nouveau GPU"
  scripts/config --module CONFIG_DRM_NOUVEAU
  scripts/config --enable CONFIG_NOUVEAU_LEGACY_CTX_SUPPORT
  scripts/config --enable CONFIG_NOUVEAU_PLATFORM_DRIVER
  scripts/config --set-val CONFIG_NOUVEAU_DEBUG 3
  scripts/config --set-val CONFIG_NOUVEAU_DEBUG_DEFAULT 3
  scripts/config --enable CONFIG_NOUVEAU_DEBUG_MMU
  scripts/config --enable CONFIG_NOUVEAU_DEBUG_PUSH
  scripts/config --enable CONFIG_DRM_NOUVEAU_BACKLIGHT
  scripts/config --enable CONFIG_DRM_NOUVEAU_SVM

  sleep 2s

  # Enable vbox/virtio/vkms/vmwgfx/xen
  msg2 "Enable vbox/virtio/vkms/vmwgfx/xen"
  # Vbox
  echo "Enable Vbox"
  scripts/config --module CONFIG_DRM_VBOXVIDEO
  # Virtio
  echo "Enable Virtio"
  scripts/config --module CONFIG_DRM_VIRTIO_GPU
  # Vmwgfx
  echo "Enable Vmwgfx"
  scripts/config --module CONFIG_DRM_VMWGFX
  scripts/config --enable CONFIG_DRM_VMWGFX_FBCON

#######################################

  sleep 2s

############ Leds ############

  # Disable some leds features
  msg2 "Disable CONFIG_LEDS_RT8515"
  scripts/config --disable CONFIG_LEDS_RT8515

#######################################

  sleep 2s

############ Filesystem ############

  # Base support for filesystem
  msg2 "Enable base support for file system"
  echo "Enable DCACHE_WORD_ACCESS"
  scripts/config --enable CONFIG_DCACHE_WORD_ACCESS
  echo "Enable VALIDATE_FS_PARSER"
  scripts/config --enable CONFIG_VALIDATE_FS_PARSER
  echo "Enable FS_IOMAP"
  scripts/config --enable CONFIG_FS_IOMAP
  echo "Enable FS_MBCACHE"
  scripts/config --module CONFIG_FS_MBCACHE
  echo "Enable FS_DAX"
  scripts/config --enable CONFIG_FS_DAX
  echo "Enable FS_DAX_PMD"
  scripts/config --enable CONFIG_FS_DAX_PMD
  echo "Enable FS_DAX_LIMITED"
  scripts/config --enable CONFIG_FS_DAX_LIMITED
  echo "Enable FS_POSIX_ACL"
  scripts/config --enable CONFIG_FS_POSIX_ACL
  echo "Enable EXPORTFS"
  scripts/config --enable CONFIG_EXPORTFS
  echo "Enable EXPORTFS_BLOCK_OPS"
  scripts/config --enable CONFIG_EXPORTFS_BLOCK_OPS
  echo "Enable FILE_LOCKING"
  scripts/config --enable CONFIG_FILE_LOCKING
  echo "Enable MANDATORY_FILE_LOCKING"
  scripts/config --enable CONFIG_MANDATORY_FILE_LOCKING
  echo "Enable TMPFS"
  scripts/config --enable CONFIG_TMPFS
  echo "Enable TMPFS_POSIX_ACL"
  scripts/config --enable CONFIG_TMPFS_POSIX_ACL
  echo "Enable TMPFS_XATTR"
  scripts/config --enable CONFIG_TMPFS_XATTR
  echo "Enable TMPFS_INODE64"
  scripts/config --enable CONFIG_TMPFS_INODE64
  echo "Enable HUGETLBFS"
  scripts/config --enable CONFIG_HUGETLBFS
  echo "Enable HUGETLB_PAGE"
  scripts/config --enable CONFIG_HUGETLB_PAGE
  echo "Enable MEMFD_CREATE"
  scripts/config --enable CONFIG_MEMFD_CREATE
  echo "Enable MISC_FILESYSTEMS"
  scripts/config --enable CONFIG_MISC_FILESYSTEMS
  echo "Enable NETWORK_FILESYSTEMS"
  scripts/config --enable CONFIG_NETWORK_FILESYSTEMS
  echo "Enable GRACE_PERIOD"
  scripts/config --module CONFIG_GRACE_PERIOD
  echo "Enable LOCKD"
  scripts/config --module CONFIG_LOCKD
  echo "Enable LOCKD_V4"
  scripts/config --enable CONFIG_LOCKD_V4
  echo "Enable NFS_ACL_SUPPORT"
  scripts/config --module CONFIG_NFS_ACL_SUPPORT
  echo "Enable NFS_COMMON"
  scripts/config --enable CONFIG_NFS_COMMON
  echo "Enable IO_WQ"
  scripts/config --enable CONFIG_IO_WQ

  sleep 2s

  # Filesystem
  msg2 "Disable uneeded filesystem support"
  # Disable 9p
  echo "Disable 9p"
  scripts/config --disable CONFIG_9P_FS
  scripts/config --disable CONFIG_9P_FSCACHE
  scripts/config --disable CONFIG_9P_FS_POSIX_ACL
  scripts/config --disable CONFIG_9P_FS_SECURITY
  # Disable Adfs
  scripts/config --disable CONFIG_ADFS_FS
  scripts/config --disable CONFIG_ADFS_FS_RW
  # Disable Affs (Amiga FFS file system support)
  echo "Disable AFFS (Amiga FFS file system support)"
  scripts/config --disable CONFIG_AFFS_FS
  # Disable Afs (Andrew File System support (AFS))
  echo "Disable Afs (Andrew File System support (AFS))"
  scripts/config --disable CONFIG_AFS_FS
  scripts/config --disable CONFIG_AFS_DEBUG
  scripts/config --disable CONFIG_AFS_FSCACHE
  scripts/config --disable CONFIG_AFS_DEBUG_CURSOR
  # Disable Befs (BeOS file system (BeFS) support (read only))
  echo "Disable Befs (BeOS file system (BeFS) support (read only))"
  scripts/config --disable CONFIG_BEFS_FS
  scripts/config --disable CONFIG_BEFS_DEBUG
  # Disable Bfs (BFS file system support)
  echo "Disable Bfs (BFS file system support)"
  scripts/config --disable CONFIG_BFS_FS
  # Disable Cachefiles (Filesystem caching on files)
  echo "Disable Cachefiles (Filesystem caching on files)"
  scripts/config --disable CONFIG_CACHEFILES
  scripts/config --disable CONFIG_CACHEFILES_DEBUG
  scripts/config --disable CONFIG_CACHEFILES_HISTOGRAM
  # Disable Ceph (Ceph distributed file system)
  echo "Disable Ceph (Ceph distributed file system)"
  scripts/config --disable CONFIG_CEPH_FS
  scripts/config --disable CONFIG_CEPH_FSCACHE
  scripts/config --disable CONFIG_CEPH_FS_POSIX_ACL
  scripts/config --disable CONFIG_CEPH_FS_SECURITY_LABEL
  # Disable coda (Coda file system support (advanced network fs))
  echo "Disable coda (Coda file system support (advanced network fs))"
  scripts/config --disable CONFIG_CODA_FS
  # Disable Configfs (Userspace-driven configuration filesystem)
  echo "Disable Configfs (Userspace-driven configuration filesystem)"
  scripts/config --disable CONFIG_CONFIGFS_FS
  # Disable Cramfs (Compressed ROM file system support (cramfs))
  echo "Disable Cramfs (Compressed ROM file system support (cramfs))"
  scripts/config --disable CONFIG_CRAMFS
  scripts/config --disable CONFIG_CRAMFS_BLOCKDEV
  scripts/config --disable CONFIG_CRAMFS_MTD
  # Disable Dlm (Distributed Lock Manager (DLM))
  echo "Disable Dlm (Distributed Lock Manager (DLM))"
  scripts/config --disable CONFIG_DLM
  scripts/config --disable CONFIG_DLM_DEBUG
  # Disable Efs (EFS file system support (read only))
  echo "Disable Efs (EFS file system support (read only))"
  scripts/config --disable CONFIG_EFS_FS
  # Disable Erofs
  echo "Disable Erofs"
  scripts/config --disable CONFIG_EROFS_FS
  scripts/config --disable CONFIG_EROFS_FS_DEBUG
  scripts/config --disable CONFIG_EROFS_FS_XATTR
  scripts/config --disable CONFIG_EROFS_FS_POSIX_ACL
  scripts/config --disable CONFIG_EROFS_FS_SECURITY
  scripts/config --disable CONFIG_EROFS_FS_ZIP
  scripts/config --disable CONFIG_EROFS_FS_CLUSTER_PAGE_LIMIT
  # Disable ext2 support
  echo "Disable ext2"
  scripts/config --disable CONFIG_EXT2_FS
  scripts/config --disable CONFIG_EXT2_FS_XATTR
  scripts/config --disable CONFIG_EXT2_FS_POSIX_ACL
  scripts/config --disable CONFIG_EXT2_FS_SECURITY
  # Disable ext3 support
  echo "Disable ext3"
  scripts/config --disable CONFIG_EXT3_FS
  scripts/config --disable CONFIG_EXT3_FS_POSIX_ACL
  scripts/config --disable CONFIG_EXT3_FS_SECURITY
  # Disable F2fs
  echo "Disable F2fs"
  scripts/config --disable CONFIG_F2FS_FS
  scripts/config --disable CONFIG_F2FS_STAT_FS
  scripts/config --disable CONFIG_F2FS_FS_XATTR
  scripts/config --disable CONFIG_F2FS_FS_POSIX_ACL
  scripts/config --disable CONFIG_F2FS_FS_SECURITY
  scripts/config --disable CONFIG_F2FS_CHECK_FS
  scripts/config --disable CONFIG_F2FS_IO_TRACE
  scripts/config --disable CONFIG_F2FS_FAULT_INJECTION
  scripts/config --disable CONFIG_F2FS_FS_COMPRESSION
  scripts/config --disable CONFIG_F2FS_FS_LZO
  scripts/config --disable CONFIG_F2FS_FS_LZ4
  scripts/config --disable CONFIG_F2FS_FS_ZSTD
  scripts/config --disable CONFIG_F2FS_FS_LZORLE
  # Disable FreeVxfs
  echo "Disable FreeVxfs"
  scripts/config --disable CONFIG_VXFS_FS
  # Disable Fscache (General filesystem local caching manager)
  echo "Disable Fscache (General filesystem local caching manager)"
  scripts/config --disable CONFIG_FSCACHE
  scripts/config --disable CONFIG_FSCACHE_STATS
  scripts/config --disable CONFIG_FSCACHE_HISTOGRAM
  scripts/config --disable CONFIG_FSCACHE_DEBUG
  scripts/config --disable CONFIG_FSCACHE_OBJECT_LIST
  # Disable Gfs2
  echo "DIsable Gfs2"
  scripts/config --disable CONFIG_GFS2_FS
  scripts/config --disable CONFIG_GFS2_FS_LOCKING_DLM
  # Disable Hfs (Apple Macintosh file system support)
  echo "Disable Hfs (Apple Macintosh file system support)"
  scripts/config --disable CONFIG_HFS_FS
  # Disable Hfsplus (Apple Extended HFS file system support)
  echo "Disable Hfsplus (Apple Extended HFS file system support)"
  scripts/config --disable CONFIG_HFSPLUS_FS
  # Disable Hpfs (OS/2 HPFS file system support)
  echo "Disable Hpfs (OS/2 HPFS file system support)"
  scripts/config --disable CONFIG_HPFS_FS
  # Disable Isofs (ISO 9660 CDROM file system support)
  echo "Disable Isofs (ISO 9660 CDROM file system support)"
  scripts/config --disable CONFIG_ISO9660_FS
  scripts/config --disable CONFIG_JOLIET
  scripts/config --disable CONFIG_ZISOFS
  # Disable Jffs2
  echo "Disable Jffs2"
  scripts/config --disable CONFIG_JFFS2_FS
  scripts/config --disable CONFIG_JFFS2_FS_DEBUG
  scripts/config --disable CONFIG_JFFS2_FS_WRITEBUFFER
  scripts/config --disable CONFIG_JFFS2_FS_WBUF_VERIFY
  scripts/config --disable CONFIG_JFFS2_SUMMARY
  scripts/config --disable CONFIG_JFFS2_FS_XATTR
  scripts/config --disable CONFIG_JFFS2_FS_POSIX_ACL
  scripts/config --disable CONFIG_JFFS2_FS_SECURITY
  scripts/config --disable CONFIG_JFFS2_COMPRESSION_OPTIONS
  scripts/config --disable CONFIG_JFFS2_ZLIB
  scripts/config --disable CONFIG_JFFS2_LZO
  scripts/config --disable CONFIG_JFFS2_RTIME
  scripts/config --disable CONFIG_JFFS2_RUBIN
  scripts/config --disable CONFIG_JFFS2_CMODE_NONE
  scripts/config --disable CONFIG_JFFS2_CMODE_PRIORITY
  scripts/config --disable CONFIG_JFFS2_CMODE_SIZE
  scripts/config --disable CONFIG_JFFS2_CMODE_FAVOURLZO
  # Disable Jfs
  echo "Disable Jfs"
  scripts/config --disable CONFIG_JFS_FS
  scripts/config --disable CONFIG_JFS_POSIX_ACL
  scripts/config --disable CONFIG_JFS_SECURITY
  scripts/config --disable CONFIG_JFS_DEBUG
  scripts/config --disable CONFIG_JFS_STATISTICS
  # Disable Kernfs
  echo "Disable Kernfs"
  scripts/config --disable CONFIG_KERNFS
  # Disable Minix
  echo "Disable Minix"
  scripts/config --disable CONFIG_MINIX_FS
  scripts/config --disable CONFIG_MINIX_FS_NATIVE_ENDIAN
  scripts/config --disable CONFIG_MINIX_FS_BIG_ENDIAN_16BIT_INDEXED
  # Disable Notify
  echo "Disable Notify"
  scripts/config --disable CONFIG_FSNOTIFY
  # Disable Ocfs2
  echo "Disable Ocfs2"
  scripts/config --disable CONFIG_OCFS2_FS
  scripts/config --disable CONFIG_OCFS2_FS_O2CB
  scripts/config --disable CONFIG_OCFS2_FS_USERSPACE_CLUSTER
  scripts/config --disable CONFIG_OCFS2_FS_STATS
  scripts/config --disable CONFIG_OCFS2_DEBUG_MASKLOG
  scripts/config --disable CONFIG_OCFS2_DEBUG_FS
  # Disable Orangefs
  echo "Disable Orangefs"
  scripts/config --disable CONFIG_ORANGEFS_FS
  # Disable Overlayfs
  echo "Disable Overlayfs"
  scripts/config --disable CONFIG_OVERLAY_FS
  scripts/config --disable CONFIG_OVERLAY_FS_REDIRECT_DIR
  scripts/config --disable CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW
  scripts/config --disable CONFIG_OVERLAY_FS_INDEX
  scripts/config --disable CONFIG_OVERLAY_FS_NFS_EXPORT
  scripts/config --disable CONFIG_OVERLAY_FS_XINO_AUTO
  scripts/config --disable CONFIG_OVERLAY_FS_METACOPY
  # Disable Pstore
  echo "Disable Pstore"
  scripts/config --disable CONFIG_PSTORE
  scripts/config --disable CONFIG_PSTORE_DEFAULT_KMSG_BYTES
  scripts/config --disable CONFIG_PSTORE_DEFLATE_COMPRESS
  scripts/config --disable CONFIG_PSTORE_LZO_COMPRESS
  scripts/config --disable CONFIG_PSTORE_LZ4_COMPRESS
  scripts/config --disable CONFIG_PSTORE_LZ4HC_COMPRESS
  scripts/config --disable CONFIG_PSTORE_842_COMPRESS
  scripts/config --disable CONFIG_PSTORE_ZSTD_COMPRESS
  scripts/config --disable CONFIG_PSTORE_COMPRESS
  scripts/config --disable CONFIG_PSTORE_COMPRESS_DEFAULT
  scripts/config --disable CONFIG_PSTORE_CONSOLE
  scripts/config --disable CONFIG_PSTORE_PMSG
  scripts/config --disable CONFIG_PSTORE_FTRACE
  scripts/config --disable CONFIG_PSTORE_RAM
  scripts/config --disable CONFIG_PSTORE_ZONE
  scripts/config --disable CONFIG_PSTORE_BLK
  scripts/config --disable CONFIG_PSTORE_BLK_BLKDEV
  scripts/config --disable CONFIG_PSTORE_BLK_KMSG_SIZE
  scripts/config --disable CONFIG_PSTORE_BLK_MAX_REASON
  scripts/config --disable CONFIG_PSTORE_BLK_PMSG_SIZE
  scripts/config --disable CONFIG_PSTORE_BLK_CONSOLE_SIZE
  scripts/config --disable CONFIG_PSTORE_BLK_FTRACE_SIZE
  # Disable Qnx4
  echo "Disable Qnx4"
  scripts/config --disable CONFIG_QNX4FS_FS
  # Disable Qnx6
  echo "Disable Qnx6"
  scripts/config --disable CONFIG_QNX6FS_FS
  scripts/config --disable CONFIG_QNX6FS_DEBUG
  # Disable Quota
  echo "Disable Quota"
  scripts/config --disable CONFIG_QUOTA
  scripts/config --disable CONFIG_QUOTA_NETLINK_INTERFACE
  scripts/config --disable CONFIG_PRINT_QUOTA_WARNING
  scripts/config --disable CONFIG_QUOTA_DEBUG
  scripts/config --disable CONFIG_QUOTA_TREE
  scripts/config --disable CONFIG_QFMT_V1
  scripts/config --disable CONFIG_QFMT_V2
  scripts/config --disable CONFIG_QUOTACTL
  # Disable Reiserfs
  echo "Disable Reiserfs"
  scripts/config --disable CONFIG_REISERFS_FS
  scripts/config --disable CONFIG_REISERFS_CHECK
  scripts/config --disable CONFIG_REISERFS_PROC_INFO
  scripts/config --disable CONFIG_REISERFS_FS_XATTR
  scripts/config --disable CONFIG_REISERFS_FS_POSIX_ACL
  scripts/config --disable CONFIG_REISERFS_FS_SECURITY
  # Disable Romfs
  echo "Disable Romfs"
  scripts/config --disable CONFIG_ROMFS_FS
  # Disable Squashfs
  echo "Disable Squashfs"
  scripts/config --disable CONFIG_SQUASHFS
  scripts/config --disable CONFIG_SQUASHFS_FILE_CACHE
  scripts/config --disable CONFIG_SQUASHFS_FILE_DIRECT
  scripts/config --disable CONFIG_SQUASHFS_DECOMP_SINGLE
  scripts/config --disable CONFIG_SQUASHFS_DECOMP_MULTI
  scripts/config --disable CONFIG_SQUASHFS_DECOMP_MULTI_PERCPU
  scripts/config --disable CONFIG_SQUASHFS_XATTR
  scripts/config --disable CONFIG_SQUASHFS_ZLIB
  scripts/config --disable CONFIG_SQUASHFS_LZ4
  scripts/config --disable CONFIG_SQUASHFS_LZO
  scripts/config --disable CONFIG_SQUASHFS_XZ
  scripts/config --disable CONFIG_SQUASHFS_ZSTD
  scripts/config --disable CONFIG_SQUASHFS_4K_DEVBLK_SIZE
  scripts/config --disable CONFIG_SQUASHFS_EMBEDDED
  scripts/config --disable CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE
  # Disable Sysv
  echo "Disable Sysv"
  scripts/config --disable CONFIG_SYSV_FS
  # Disable Ubifs
  echo "Disable Ubifs"
  scripts/config --disable CONFIG_UBIFS_FS
  scripts/config --disable CONFIG_UBIFS_FS_ADVANCED_COMPR
  scripts/config --disable CONFIG_UBIFS_FS_LZO
  scripts/config --disable CONFIG_UBIFS_FS_ZLIB
  scripts/config --disable CONFIG_UBIFS_FS_ZSTD
  scripts/config --disable CONFIG_UBIFS_ATIME_SUPPORT
  scripts/config --disable CONFIG_UBIFS_FS_XATTR
  scripts/config --disable CONFIG_UBIFS_FS_SECURITY
  scripts/config --disable CONFIG_UBIFS_FS_AUTHENTICATION
  # Disable Udf
  echo "Disable Udf"
  scripts/config --disable CONFIG_UDF_FS
  # Disable Ufs
  echo "Disable Ufs"
  scripts/config --disable CONFIG_UFS_FS
  scripts/config --disable CONFIG_UFS_FS_WRITE
  scripts/config --disable CONFIG_UFS_DEBUG
  # Disable Xfs
  echo "Disable Xfs"
  scripts/config --disable CONFIG_XFS_FS
  scripts/config --disable CONFIG_XFS_SUPPORT_V4
  scripts/config --disable CONFIG_XFS_QUOTA
  scripts/config --disable CONFIG_XFS_POSIX_ACL
  scripts/config --disable CONFIG_XFS_RT
  scripts/config --disable CONFIG_XFS_ONLINE_SCRUB
  scripts/config --disable CONFIG_XFS_ONLINE_REPAIR
  scripts/config --disable CONFIG_XFS_WARN
  scripts/config --disable CONFIG_XFS_DEBUG
  scripts/config --disable CONFIG_XFS_ASSERT_FATAL
  # Disable Zonefs
  echo "Disable Zonefs"
  scripts/config --disable CONFIG_ZONEFS_FS

  sleep 2s

  # Enable Needed filesystem
  msg2 "Enable Needed filesystem"
  # Autofs (Kernel automounter support (supports v3, v4 and v5))
  echo "Enable Autofs (Kernel automounter support (supports v3, v4 and v5))"
  scripts/config --enable CONFIG_AUTOFS4_FS
  scripts/config --enable CONFIG_AUTOFS_FS
  # Btrfs
  echo "Enable Btrfs"
  scripts/config --enable CONFIG_BTRFS_FS
  scripts/config --enable CONFIG_BTRFS_FS_POSIX_ACL
  # Cifs
  echo "Enable Cifs"
  scripts/config --module CONFIG_CIFS
  scripts/config --enable CONFIG_CIFS_ALLOW_INSECURE_LEGACY
  scripts/config --enable CONFIG_CIFS_WEAK_PW_HASH
  scripts/config --enable CONFIG_CIFS_UPCALL
  scripts/config --enable CONFIG_CIFS_XATTR
  scripts/config --enable CONFIG_CIFS_POSIX
  scripts/config --enable CONFIG_CIFS_DFS_UPCALL
  scripts/config --enable CONFIG_CIFS_SWN_UPCALL
  scripts/config --enable CONFIG_CIFS_NFSD_EXPORT
  scripts/config --enable CONFIG_CIFS_SMB_DIRECT
  scripts/config --enable CONFIG_CIFS_FSCACHE
  scripts/config --enable CONFIG_CIFS_ROOT
  # Crypto
  echo "Enable Crypto"
  scripts/config --enable CONFIG_FS_ENCRYPTION
  scripts/config --module CONFIG_FS_ENCRYPTION_ALGS
  scripts/config --enable CONFIG_FS_ENCRYPTION_INLINE_CRYPT
  # Ecryptfs
  echo "Enable Ecryptfs"
  scripts/config --enable CONFIG_ECRYPT_FS
  scripts/config --enable CONFIG_ECRYPT_FS_MESSAGING
  # Efivarfs
  echo "Enable Efivarfs"
  scripts/config --enable CONFIG_EFIVAR_FS
  # Exfat
  echo "Enable Exfat"
  scripts/config --enable CONFIG_EXFAT_FS
  scripts/config --set-val CONFIG_EXFAT_DEFAULT_IOCHARSET "utf8"
  # Fully support ext4
  echo "Enable ext4"
  scripts/config --enable CONFIG_EXT4_FS
  scripts/config --enable CONFIG_EXT4_USE_FOR_EXT2
  scripts/config --enable CONFIG_EXT4_FS_POSIX_ACL
  scripts/config --enable CONFIG_EXT4_FS_SECURITY
  # Fat
  echo "Enable Fat"
  scripts/config --module CONFIG_FAT_FS
  scripts/config --module CONFIG_MSDOS_FS
  scripts/config --module CONFIG_VFAT_FS
  scripts/config --set-val CONFIG_FAT_DEFAULT_CODEPAGE 437
  scripts/config --set-val CONFIG_FAT_DEFAULT_IOCHARSET "ascii"
  scripts/config --enable CONFIG_FAT_DEFAULT_UTF8
  # Fuse
  echo "Enable Fuse"
  scripts/config --module CONFIG_FUSE_FS
  scripts/config --module CONFIG_CUSE
  scripts/config --module CONFIG_VIRTIO_FS
  scripts/config --enable CONFIG_FUSE_DAX
  # Jbd2
  echo "Enable Jbd2"
  scripts/config --enable CONFIG_JBD2
  # Nfs
  echo "Enable Nfs"
  scripts/config --module CONFIG_CONFIG_NFS_FS
  scripts/config --module CONFIG_CONFIG_NFS_V2
  scripts/config --module CONFIG_CONFIG_NFS_V3
  scripts/config --enable CONFIG_CONFIG_NFS_V3_ACL
  scripts/config --module CONFIG_CONFIG_NFS_V4
  scripts/config --enable CONFIG_CONFIG_NFS_SWAP
  scripts/config --enable CONFIG_CONFIG_NFS_V4_1
  scripts/config --enable CONFIG_CONFIG_NFS_V4_2
  scripts/config --module CONFIG_CONFIG_PNFS_FILE_LAYOUT
  scripts/config --module CONFIG_CONFIG_PNFS_BLOCK
  scripts/config --module CONFIG_CONFIG_PNFS_FLEXFILE_LAYOUT
  scripts/config --set-val CONFIG_CONFIG_NFS_V4_1_IMPLEMENTATION_ID_DOMAIN "kernel.org"
  scripts/config --enable CONFIG_CONFIG_NFS_V4_1_MIGRATION
  scripts/config --enable CONFIG_CONFIG_NFS_V4_SECURITY_LABEL
  scripts/config --enable CONFIG_CONFIG_NFS_FSCACHE
  scripts/config --enable CONFIG_CONFIG_NFS_USE_LEGACY_DNS
  scripts/config --enable CONFIG_CONFIG_NFS_USE_KERNEL_DNS
  scripts/config --enable CONFIG_CONFIG_NFS_DISABLE_UDP_SUPPORT
  scripts/config --enable CONFIG_CONFIG_NFS_V4_2_READ_PLUS
  # Nfsd
  echo "Enable Nfsd"
  scripts/config --module CONFIG_NFSD
  scripts/config --enable CONFIG_NFSD_V2_ACL
  scripts/config --enable CONFIG_NFSD_V3
  scripts/config --enable CONFIG_NFSD_V3_ACL
  scripts/config --enable CONFIG_NFSD_V4
  scripts/config --enable CONFIG_NFSD_PNFS
  scripts/config --enable CONFIG_NFSD_BLOCKLAYOUT
  scripts/config --enable CONFIG_NFSD_SCSILAYOUT
  scripts/config --enable CONFIG_NFSD_FLEXFILELAYOUT
  scripts/config --enable CONFIG_NFSD_V4_2_INTER_SSC
  scripts/config --enable CONFIG_NFSD_V4_SECURITY_LABEL
  # Nilfs2
  echo "Enable Nilfs2"
  scripts/config --module CONFIG_NILFS2_FS
  # Proc
  echo "Enable proc"
  scripts/config --enable CONFIG_PROC_FS
  scripts/config --enable CONFIG_PROC_KCORE
  scripts/config --enable CONFIG_PROC_VMCORE
  scripts/config --enable CONFIG_PROC_VMCORE_DEVICE_DUMP
  scripts/config --enable CONFIG_PROC_SYSCTL
  scripts/config --enable CONFIG_PROC_PAGE_MONITOR
  scripts/config --enable CONFIG_PROC_CHILDREN
  scripts/config --enable CONFIG_PROC_PID_ARCH_STATUS
  scripts/config --enable CONFIG_PROC_CPU_RESCTRL
  # Sysfs
  echo "Enable Sysfs"
  scripts/config --enable CONFIG_SYSFS
  # Unicode
  echo "Enable UNicode"
  scripts/config --enable CONFIG_UNICODE
  scripts/config --enable CONFIG_UNICODE_NORMALIZATION_SELFTEST
  # Vboxfs
  echo "Enable Vboxfs"
  scripts/config --enable CONFIG_VBOXSF_FS

#######################################

  sleep 2s

############ Radio ############

  # Disable Radio driver
  msg2 "Disable Radio driver"
  scripts/config --disable CONFIG_MEDIA_RADIO_SUPPORT
  scripts/config --disable CONFIG_RADIO_ADAPTERS
  scripts/config --disable CONFIG_RADIO_TEA575X
  scripts/config --disable CONFIG_RADIO_SI4713
  scripts/config --disable CONFIG_RADIO_SI476X
  scripts/config --disable CONFIG_USB_MR800
  scripts/config --disable CONFIG_USB_DSBR
  scripts/config --disable CONFIG_RADIO_MAXIRADIO
  scripts/config --disable CONFIG_RADIO_SHARK
  scripts/config --disable CONFIG_RADIO_SHARK2
  scripts/config --disable CONFIG_USB_KEENE
  scripts/config --disable CONFIG_USB_RAREMONO
  scripts/config --disable CONFIG_USB_MA901
  scripts/config --disable CONFIG_RADIO_TEA5764
  scripts/config --disable CONFIG_RADIO_TEA5764_XTAL
  scripts/config --disable CONFIG_RADIO_SAA7706H
  scripts/config --disable CONFIG_RADIO_TEF6862
  scripts/config --disable CONFIG_RADIO_TIMBERDALE
  scripts/config --disable CONFIG_RADIO_WL1273
  scripts/config --disable CONFIG_V4L_RADIO_ISA_DRIVERS
  scripts/config --disable CONFIG_RADIO_ISA
  scripts/config --disable CONFIG_RADIO_CADET
  scripts/config --disable CONFIG_RADIO_RTRACK
  scripts/config --disable CONFIG_RADIO_RTRACK_PORT
  scripts/config --disable CONFIG_RADIO_RTRACK2
  scripts/config --disable CONFIG_RADIO_RTRACK2_PORT
  scripts/config --disable CONFIG_RADIO_AZTECH
  scripts/config --disable CONFIG_RADIO_AZTECH_PORT
  scripts/config --disable CONFIG_RADIO_GEMTEK
  scripts/config --disable CONFIG_RADIO_GEMTEK_PORT
  scripts/config --disable CONFIG_RADIO_GEMTEK_PROBE
  scripts/config --disable CONFIG_RADIO_MIROPCM20
  scripts/config --disable CONFIG_RADIO_SF16FMI
  scripts/config --disable CONFIG_RADIO_SF16FMR2
  scripts/config --disable CONFIG_RADIO_TERRATEC
  scripts/config --disable CONFIG_RADIO_TRUST
  scripts/config --disable CONFIG_RADIO_TRUST_PORT
  scripts/config --disable CONFIG_RADIO_TYPHOON
  scripts/config --disable CONFIG_RADIO_TYPHOON_PORT
  scripts/config --disable CONFIG_RADIO_TYPHOON_MUTEFREQ
  scripts/config --disable CONFIG_RADIO_ZOLTRIX
  scripts/config --disable CONFIG_RADIO_ZOLTRIX_PORT
  scripts/config --disable CONFIG_RADIO_SI470X
  scripts/config --disable CONFIG_USB_SI470X
  scripts/config --disable CONFIG_I2C_SI470X
  scripts/config --disable CONFIG_USB_SI4713
  scripts/config --disable CONFIG_PLATFORM_SI4713
  scripts/config --disable CONFIG_I2C_SI4713
  scripts/config --disable CONFIG_RADIO_WL128X

#######################################

  sleep 2s

############ Tv Tunners ############

  # Disable TV Tuners
  msg2 "Disable TV Tuners"
  scripts/config --disable CONFIG_MEDIA_DIGITAL_TV_SUPPORT
  scripts/config --disable CONFIG_MEDIA_TUNER
  scripts/config --disable CONFIG_MEDIA_TUNER_SIMPLE
  scripts/config --disable CONFIG_MEDIA_TUNER_TDA18250
  scripts/config --disable CONFIG_MEDIA_TUNER_TDA8290
  scripts/config --disable CONFIG_MEDIA_TUNER_TDA827X
  scripts/config --disable CONFIG_MEDIA_TUNER_TDA18271
  scripts/config --disable CONFIG_MEDIA_TUNER_TDA9887
  scripts/config --disable CONFIG_MEDIA_TUNER_TEA5761
  scripts/config --disable CONFIG_MEDIA_TUNER_TEA5767
  scripts/config --disable CONFIG_MEDIA_TUNER_MSI001
  scripts/config --disable CONFIG_MEDIA_TUNER_MT20XX
  scripts/config --disable CONFIG_MEDIA_TUNER_MT2060
  scripts/config --disable CONFIG_MEDIA_TUNER_MT2063
  scripts/config --disable CONFIG_MEDIA_TUNER_MT2266
  scripts/config --disable CONFIG_MEDIA_TUNER_MT2131
  scripts/config --disable CONFIG_MEDIA_TUNER_QT1010
  scripts/config --disable CONFIG_MEDIA_TUNER_XC2028
  scripts/config --disable CONFIG_MEDIA_TUNER_XC5000
  scripts/config --disable CONFIG_MEDIA_TUNER_XC4000
  scripts/config --disable CONFIG_MEDIA_TUNER_MXL5005S
  scripts/config --disable CONFIG_MEDIA_TUNER_MXL5007T
  scripts/config --disable CONFIG_MEDIA_TUNER_MC44S803
  scripts/config --disable CONFIG_MEDIA_TUNER_MAX2165
  scripts/config --disable CONFIG_MEDIA_TUNER_TDA18218
  scripts/config --disable CONFIG_MEDIA_TUNER_FC0011
  scripts/config --disable CONFIG_MEDIA_TUNER_FC0012
  scripts/config --disable CONFIG_MEDIA_TUNER_FC0013
  scripts/config --disable CONFIG_MEDIA_TUNER_TDA18212
  scripts/config --disable CONFIG_MEDIA_TUNER_E4000
  scripts/config --disable CONFIG_MEDIA_TUNER_FC2580
  scripts/config --disable CONFIG_MEDIA_TUNER_M88RS6000T
  scripts/config --disable CONFIG_MEDIA_TUNER_TUA9001
  scripts/config --disable CONFIG_MEDIA_TUNER_SI2157
  scripts/config --disable CONFIG_MEDIA_TUNER_IT913X
  scripts/config --disable CONFIG_MEDIA_TUNER_R820T
  scripts/config --disable CONFIG_MEDIA_TUNER_MXL301RF
  scripts/config --disable CONFIG_MEDIA_TUNER_QM1D1C0042
  scripts/config --disable CONFIG_MEDIA_TUNER_QM1D1B0004

#######################################

  sleep 2s

############ Apple drivers ############

  # Disable Apple drivers
  msg2 "Disable Apple drivers... Please dont buy apple stuff!.."
  scripts/config --disable CONFIG_HID_APPLE
  scripts/config --disable CONFIG_HID_APPLEIR
  scripts/config --disable CONFIG_MACINTOSH_DRIVERS
  scripts/config --disable CONFIG_ADB
  scripts/config --disable CONFIG_ADB_MACII
  scripts/config --disable CONFIG_ADB_IOP
  scripts/config --disable CONFIG_ADB_CUDA
  scripts/config --disable CONFIG_ADB_PMU
  scripts/config --disable CONFIG_ADB_PMU_LED
  scripts/config --disable CONFIG_ADB_PMU_LED_DISK
  scripts/config --disable CONFIG_PMAC_SMU
  scripts/config --disable CONFIG_PMAC_APM_EMU
  scripts/config --disable CONFIG_PMAC_MEDIABAY
  scripts/config --disable CONFIG_PMAC_BACKLIGHT
  scripts/config --disable CONFIG_PMAC_BACKLIGHT_LEGACY
  scripts/config --disable CONFIG_ADB_MACIO
  scripts/config --disable CONFIG_INPUT_ADBHID
  scripts/config --disable CONFIG_MAC_EMUMOUSEBTN
  scripts/config --disable CONFIG_THERM_WINDTUNNEL
  scripts/config --disable CONFIG_THERM_ADT746X
  scripts/config --disable CONFIG_WINDFARM
  scripts/config --disable CONFIG_WINDFARM_PM81
  scripts/config --disable CONFIG_WINDFARM_PM72
  scripts/config --disable CONFIG_WINDFARM_RM31
  scripts/config --disable CONFIG_WINDFARM_PM91
  scripts/config --disable CONFIG_WINDFARM_PM112
  scripts/config --disable CONFIG_WINDFARM_PM121
  scripts/config --disable CONFIG_ANSLCD
  scripts/config --disable CONFIG_PMAC_RACKMETER
  scripts/config --disable CONFIG_SENSORS_AMS
  scripts/config --disable CONFIG_SENSORS_AMS_PMU
  scripts/config --disable CONFIG_SENSORS_AMS_I2C
  scripts/config --disable CONFIG_APPLE_GMUX
  scripts/config --disable CONFIG_HID_MAGICMOUSE

#######################################

  sleep 2s

############ Drivers/iio ############

  # Disable uneeded iio drivers
  msg2 "Disable uneeded iio drivers"
  # Accelerometers
  echo "Disable accelerometers"
  scripts/config --disable CONFIG_ADIS16201
  scripts/config --disable CONFIG_ADIS16209
  scripts/config --disable CONFIG_ADXL345
  scripts/config --disable CONFIG_ADXL345_I2C
  scripts/config --disable CONFIG_ADXL345_SPI
  scripts/config --disable CONFIG_ADXL372
  scripts/config --disable CONFIG_ADXL372_SPI
  scripts/config --disable CONFIG_ADXL372_I2C
  scripts/config --disable CONFIG_BMA180
  scripts/config --disable CONFIG_BMA220
  scripts/config --disable CONFIG_BMA400
  scripts/config --disable CONFIG_BMA400_I2C
  scripts/config --disable CONFIG_BMA400_SPI
  scripts/config --disable CONFIG_BMC150_ACCEL
  scripts/config --disable CONFIG_BMC150_ACCEL_I2C
  scripts/config --disable CONFIG_BMC150_ACCEL_SPI
  scripts/config --disable CONFIG_DA280
  scripts/config --disable CONFIG_DA311
  scripts/config --disable CONFIG_DMARD06
  scripts/config --disable CONFIG_DMARD09
  scripts/config --disable CONFIG_DMARD10
  scripts/config --disable CONFIG_HID_SENSOR_ACCEL_3D
  scripts/config --disable CONFIG_IIO_CROS_EC_ACCEL_LEGACY
  scripts/config --disable CONFIG_IIO_ST_ACCEL_3AXIS
  scripts/config --disable CONFIG_IIO_ST_ACCEL_I2C_3AXIS
  scripts/config --disable CONFIG_IIO_ST_ACCEL_SPI_3AXIS
  scripts/config --disable CONFIG_KXSD9
  scripts/config --disable CONFIG_KXSD9_SPI
  scripts/config --disable CONFIG_KXSD9_I2C
  scripts/config --disable CONFIG_KXCJK1013
  scripts/config --disable CONFIG_MC3230
  scripts/config --disable CONFIG_MMA7455
  scripts/config --disable CONFIG_MMA7455_I2C
  scripts/config --disable CONFIG_MMA7455_SPI
  scripts/config --disable CONFIG_MMA7660
  scripts/config --disable CONFIG_MMA8452
  scripts/config --disable CONFIG_MMA9551_CORE
  scripts/config --disable CONFIG_MMA9551
  scripts/config --disable CONFIG_MMA9553
  scripts/config --disable CONFIG_MXC4005
  scripts/config --disable CONFIG_MXC6255
  scripts/config --disable CONFIG_SCA3000
  scripts/config --disable CONFIG_STK8312
  scripts/config --disable CONFIG_STK8BA50
  # Adc (Analog to digital converters)
  echo "Disable Adc (Analog to digital converters)"
  scripts/config --disable CONFIG_AB8500_GPADC
  scripts/config --disable CONFIG_AD_SIGMA_DELTA
  scripts/config --disable CONFIG_AD7091R5
  scripts/config --disable CONFIG_AD7124
  scripts/config --disable CONFIG_AD7192
  scripts/config --disable CONFIG_AD7266
  scripts/config --disable CONFIG_AD7291
  scripts/config --disable CONFIG_AD7292
  scripts/config --disable CONFIG_AD7298
  scripts/config --disable CONFIG_AD7476
  scripts/config --disable CONFIG_AD7606
  scripts/config --disable CONFIG_AD7606_IFACE_PARALLEL
  scripts/config --disable CONFIG_AD7606_IFACE_SPI
  scripts/config --disable CONFIG_AD7766
  scripts/config --disable CONFIG_AD7768_1
  scripts/config --disable CONFIG_AD7780
  scripts/config --disable CONFIG_AD7791
  scripts/config --disable CONFIG_AD7793
  scripts/config --disable CONFIG_AD7887
  scripts/config --disable CONFIG_AD7923
  scripts/config --disable CONFIG_AD7949
  scripts/config --disable CONFIG_AD799X
  scripts/config --disable CONFIG_AD9467
  scripts/config --disable CONFIG_ADI_AXI_ADC
  scripts/config --disable CONFIG_ASPEED_ADC
  scripts/config --disable CONFIG_AT91_ADC
  scripts/config --disable CONFIG_AT91_SAMA5D2_ADC
  scripts/config --disable CONFIG_AXP20X_ADC
  scripts/config --disable CONFIG_AXP288_ADC
  scripts/config --disable CONFIG_BCM_IPROC_ADC
  scripts/config --disable CONFIG_BERLIN2_ADC
  scripts/config --disable CONFIG_CC10001_ADC
  scripts/config --disable CONFIG_CPCAP_ADC
  scripts/config --disable CONFIG_DA9150_GPADC
  scripts/config --disable CONFIG_DLN2_ADC
  scripts/config --disable CONFIG_ENVELOPE_DETECTOR
  scripts/config --disable CONFIG_EP93XX_ADC
  scripts/config --disable CONFIG_EXYNOS_ADC
  scripts/config --disable CONFIG_MXS_LRADC_ADC
  scripts/config --disable CONFIG_FSL_MX25_ADC
  scripts/config --disable CONFIG_HI8435
  scripts/config --disable CONFIG_HX711
  scripts/config --disable CONFIG_INA2XX_ADC
  scripts/config --disable CONFIG_INGENIC_ADC
  scripts/config --disable CONFIG_INTEL_MRFLD_ADC
  scripts/config --disable CONFIG_IMX7D_ADC
  scripts/config --disable CONFIG_LP8788_ADC
  scripts/config --disable CONFIG_LPC18XX_ADC
  scripts/config --disable CONFIG_LPC32XX_ADC
  scripts/config --disable CONFIG_LTC2471
  scripts/config --disable CONFIG_LTC2485
  scripts/config --disable CONFIG_LTC2496
  scripts/config --disable CONFIG_LTC2497
  scripts/config --disable CONFIG_MAX1027
  scripts/config --disable CONFIG_MAX11100
  scripts/config --disable CONFIG_MAX1118
  scripts/config --disable CONFIG_MAX1241
  scripts/config --disable CONFIG_MAX1363
  scripts/config --disable CONFIG_MAX9611
  scripts/config --disable CONFIG_MCP320X
  scripts/config --disable CONFIG_MCP3422
  scripts/config --disable CONFIG_MCP3911
  scripts/config --disable CONFIG_MEDIATEK_MT6360_ADC
  scripts/config --disable CONFIG_MEDIATEK_MT6577_AUXADC
  scripts/config --disable CONFIG_MEN_Z188_ADC
  scripts/config --disable CONFIG_MESON_SARADC
  scripts/config --disable CONFIG_MP2629_ADC
  scripts/config --disable CONFIG_NAU7802
  scripts/config --disable CONFIG_NPCM_ADC
  scripts/config --disable CONFIG_PALMAS_GPADC
  scripts/config --disable CONFIG_QCOM_VADC_COMMON
  scripts/config --disable CONFIG_QCOM_PM8XXX_XOADC
  scripts/config --disable CONFIG_QCOM_SPMI_IADC
  scripts/config --disable CONFIG_QCOM_SPMI_VADC
  scripts/config --disable CONFIG_QCOM_SPMI_ADC5
  scripts/config --disable CONFIG_RCAR_GYRO_ADC
  scripts/config --disable CONFIG_RN5T618_ADC
  scripts/config --disable CONFIG_ROCKCHIP_SARADC
  scripts/config --disable CONFIG_SC27XX_ADC
  scripts/config --disable CONFIG_SPEAR_ADC
  scripts/config --disable CONFIG_SD_ADC_MODULATOR
  scripts/config --disable CONFIG_STM32_ADC_CORE
  scripts/config --disable CONFIG_STM32_ADC
  scripts/config --disable CONFIG_STM32_DFSDM_CORE
  scripts/config --disable CONFIG_STM32_DFSDM_ADC
  scripts/config --disable CONFIG_STMPE_ADC
  scripts/config --disable CONFIG_STX104
  scripts/config --disable CONFIG_SUN4I_GPADC
  scripts/config --disable CONFIG_TI_ADC081C
  scripts/config --disable CONFIG_TI_ADC0832
  scripts/config --disable CONFIG_TI_ADC084S021
  scripts/config --disable CONFIG_TI_ADC12138
  scripts/config --disable CONFIG_TI_ADC108S102
  scripts/config --disable CONFIG_TI_ADC128S052
  scripts/config --disable CONFIG_TI_ADC161S626
  scripts/config --disable CONFIG_TI_ADS1015
  scripts/config --disable CONFIG_TI_ADS7950
  scripts/config --disable CONFIG_TI_ADS8344
  scripts/config --disable CONFIG_TI_ADS8688
  scripts/config --disable CONFIG_TI_ADS124S08
  scripts/config --disable CONFIG_TI_AM335X_ADC
  scripts/config --disable CONFIG_TI_TLC4541
  scripts/config --disable CONFIG_TWL4030_MADC
  scripts/config --disable CONFIG_TWL6030_GPADC
  scripts/config --disable CONFIG_VF610_ADC
  scripts/config --disable CONFIG_VIPERBOARD_ADC
  scripts/config --disable CONFIG_XILINX_XADC
  # Afe (Analog Front End drivers)
  echo "Disable Afe (Analog Front End drivers)"
  scripts/config --disable CONFIG_IIO_RESCALE
  # Amplifier
  echo "Disable Amplifier"
  scripts/config --disable CONFIG_AD8366
  scripts/config --disable CONFIG_HMC425
  # Buffer
  echo "Disable Buffer"
  scripts/config --disable CONFIG_IIO_BUFFER_CB
  scripts/config --disable CONFIG_IIO_BUFFER_DMA
  scripts/config --disable CONFIG_IIO_BUFFER_DMAENGINE
  scripts/config --disable CONFIG_IIO_BUFFER_HW_CONSUMER
  scripts/config --disable CONFIG_IIO_KFIFO_BUF
  scripts/config --disable CONFIG_IIO_TRIGGERED_BUFFER
  # Chemical
  echo "Disable chemical drivers"
  scripts/config --disable CONFIG_ATLAS_PH_SENSOR
  scripts/config --disable CONFIG_ATLAS_EZO_SENSOR
  scripts/config --disable CONFIG_BME680
  scripts/config --disable CONFIG_BME680_I2C
  scripts/config --disable CONFIG_BME680_SPI
  scripts/config --disable CONFIG_CCS811
  scripts/config --disable CONFIG_IAQCORE
  scripts/config --disable CONFIG_PMS7003
  scripts/config --disable CONFIG_SCD30_CORE
  scripts/config --disable CONFIG_SCD30_I2C
  scripts/config --disable CONFIG_SCD30_SERIAL
  scripts/config --disable CONFIG_SENSIRION_SGP30
  scripts/config --disable CONFIG_SPS30
  scripts/config --disable CONFIG_VZ89X
  # Dac (Digital to analog converters)
  echo "Disable Dac (Digital to analog converters)"
  scripts/config --disable CONFIG_AD5064
  scripts/config --disable CONFIG_AD5360
  scripts/config --disable CONFIG_AD5380
  scripts/config --disable CONFIG_AD5421
  scripts/config --disable CONFIG_AD5446
  scripts/config --disable CONFIG_AD5449
  scripts/config --disable CONFIG_AD5592R_BASE
  scripts/config --disable CONFIG_AD5592R
  scripts/config --disable CONFIG_AD5593R
  scripts/config --disable CONFIG_AD5504
  scripts/config --disable CONFIG_AD5624R_SPI
  scripts/config --disable CONFIG_AD5686
  scripts/config --disable CONFIG_AD5686_SPI
  scripts/config --disable CONFIG_AD5696_I2C
  scripts/config --disable CONFIG_AD5755
  scripts/config --disable CONFIG_AD5758
  scripts/config --disable CONFIG_AD5761
  scripts/config --disable CONFIG_AD5764
  scripts/config --disable CONFIG_AD5770R
  scripts/config --disable CONFIG_AD5791
  scripts/config --disable CONFIG_AD7303
  scripts/config --disable CONFIG_AD8801
  scripts/config --disable CONFIG_CIO_DAC
  scripts/config --disable CONFIG_DPOT_DAC
  scripts/config --disable CONFIG_DS4424
  scripts/config --disable CONFIG_LPC18XX_DAC
  scripts/config --disable CONFIG_LTC1660
  scripts/config --disable CONFIG_LTC2632
  scripts/config --disable CONFIG_M62332
  scripts/config --disable CONFIG_MAX517
  scripts/config --disable CONFIG_MAX5821
  scripts/config --disable CONFIG_MCP4725
  scripts/config --disable CONFIG_MCP4922
  scripts/config --disable CONFIG_STM32_DAC
  scripts/config --disable CONFIG_STM32_DAC_CORE
  scripts/config --disable CONFIG_TI_DAC082S085
  scripts/config --disable CONFIG_TI_DAC5571
  scripts/config --disable CONFIG_TI_DAC7311
  scripts/config --disable CONFIG_TI_DAC7612
  scripts/config --disable CONFIG_VF610_DAC
  # Frequency
  echo "Disable Frequency Synthesizers drivers"
  scripts/config --disable CONFIG_AD9523
  scripts/config --disable CONFIG_ADF4350
  scripts/config --disable CONFIG_ADF4371
  # Gyro
  echo "Disable Gyro drivers"
  scripts/config --disable CONFIG_ADIS16080
  scripts/config --disable CONFIG_ADIS16130
  scripts/config --disable CONFIG_ADIS16136
  scripts/config --disable CONFIG_ADIS16260
  scripts/config --disable CONFIG_ADXRS290
  scripts/config --disable CONFIG_ADXRS450
  scripts/config --disable CONFIG_BMG160
  scripts/config --disable CONFIG_BMG160_I2C
  scripts/config --disable CONFIG_BMG160_SPI
  scripts/config --disable CONFIG_FXAS21002C
  scripts/config --disable CONFIG_FXAS21002C_I2C
  scripts/config --disable CONFIG_FXAS21002C_SPI
  scripts/config --disable CONFIG_HID_SENSOR_GYRO_3D
  scripts/config --disable CONFIG_MPU3050
  scripts/config --disable CONFIG_MPU3050_I2C
  scripts/config --disable CONFIG_IIO_ST_GYRO_3AXIS
  scripts/config --disable CONFIG_IIO_ST_GYRO_I2C_3AXIS
  scripts/config --disable CONFIG_IIO_ST_GYRO_SPI_3AXIS
  scripts/config --disable CONFIG_ITG3200
  # Health
  echo "Disable Health drivers"
  scripts/config --disable CONFIG_AFE4403
  scripts/config --disable CONFIG_AFE4404
  scripts/config --disable CONFIG_MAX30100
  scripts/config --disable CONFIG_MAX30102
  # Humidity
  echo "Disable Humidity drivers"
  scripts/config --disable CONFIG_AM2315
  scripts/config --disable CONFIG_DHT11
  scripts/config --disable CONFIG_HDC100X
  scripts/config --disable CONFIG_HDC2010
  scripts/config --disable CONFIG_HID_SENSOR_HUMIDITY
  scripts/config --disable CONFIG_HTS221
  scripts/config --disable CONFIG_HTS221_I2C
  scripts/config --disable CONFIG_HTS221_SPI
  scripts/config --disable CONFIG_HTU21
  scripts/config --disable CONFIG_SI7005
  scripts/config --disable CONFIG_SI7020
  # Imu (Inertial measurement units)
  echo "Disable Imu (Inertial measurement units)"
  scripts/config --disable CONFIG_ADIS16400
  scripts/config --disable CONFIG_ADIS16460
  scripts/config --disable CONFIG_ADIS16475
  scripts/config --disable CONFIG_ADIS16480
  scripts/config --disable CONFIG_FXOS8700
  scripts/config --disable CONFIG_FXOS8700_I2C
  scripts/config --disable CONFIG_FXOS8700_SPI
  scripts/config --disable CONFIG_KMX61
  scripts/config --disable CONFIG_IIO_ADIS_LIB
  scripts/config --disable CONFIG_IIO_ADIS_LIB_BUFFER
  scripts/config --disable CONFIG_BMI160
  scripts/config --disable CONFIG_BMI160_I2C
  scripts/config --disable CONFIG_BMI160_SPI
  scripts/config --disable CONFIG_INV_ICM42600
  scripts/config --disable CONFIG_INV_ICM42600_I2C
  scripts/config --disable CONFIG_INV_ICM42600_SPI
  scripts/config --disable CONFIG_INV_MPU6050_IIO
  scripts/config --disable CONFIG_INV_MPU6050_I2C
  scripts/config --disable CONFIG_INV_MPU6050_SPI
  scripts/config --disable CONFIG_IIO_ST_LSM6DSX
  scripts/config --disable CONFIG_IIO_ST_LSM6DSX_I2C
  scripts/config --disable CONFIG_IIO_ST_LSM6DSX_SPI
  scripts/config --disable CONFIG_IIO_ST_LSM6DSX_I3C
  # Magnetometer
  echo "Disable Magnetometer drivers"
  scripts/config --disable CONFIG_AK8974
  scripts/config --disable CONFIG_AK8975
  scripts/config --disable CONFIG_AK09911
  scripts/config --disable CONFIG_BMC150_MAGN
  scripts/config --disable CONFIG_BMC150_MAGN_I2C
  scripts/config --disable CONFIG_BMC150_MAGN_SPI
  scripts/config --disable CONFIG_MAG3110
  scripts/config --disable CONFIG_HID_SENSOR_MAGNETOMETER_3D
  scripts/config --disable CONFIG_MMC35240
  scripts/config --disable CONFIG_IIO_ST_MAGN_3AXIS
  scripts/config --disable CONFIG_IIO_ST_MAGN_I2C_3AXIS
  scripts/config --disable CONFIG_IIO_ST_MAGN_SPI_3AXIS
  scripts/config --disable CONFIG_SENSORS_HMC5843
  scripts/config --disable CONFIG_SENSORS_HMC5843_I2C
  scripts/config --disable CONFIG_SENSORS_HMC5843_SPI
  scripts/config --disable CONFIG_SENSORS_RM3100
  scripts/config --disable CONFIG_SENSORS_RM3100_I2C
  scripts/config --disable CONFIG_SENSORS_RM3100_SPI
  # Multiplexer
  echo "Disable Multiplexer drivers"
  scripts/config --disable CONFIG_IIO_MUX
  # Orientation
  echo "Disable Orientation drivers"
  scripts/config --disable CONFIG_HID_SENSOR_INCLINOMETER_3D
  scripts/config --disable CONFIG_HID_SENSOR_DEVICE_ROTATION
  # Position
  echo "Disable Position drivers"
  scripts/config --disable CONFIG_IQS624_POS
  # Potentiometers
  echo "Disable Potentiometers drivers"
  scripts/config --disable CONFIG_AD5272
  scripts/config --disable CONFIG_DS1803
  scripts/config --disable CONFIG_MAX5432
  scripts/config --disable CONFIG_MAX5481
  scripts/config --disable CONFIG_MAX5487
  scripts/config --disable CONFIG_MCP4018
  scripts/config --disable CONFIG_MCP4131
  scripts/config --disable CONFIG_MCP4531
  scripts/config --disable CONFIG_MCP41010
  scripts/config --disable CONFIG_TPL0102
  # Potentiostats
  echo "Disable Potentiostats drivers"
  scripts/config --disable CONFIG_LMP91000
  # Pressure
  echo "Disable Pressure drivers"
  scripts/config --disable CONFIG_ABP060MG
  scripts/config --disable CONFIG_BMP280
  scripts/config --disable CONFIG_BMP280_I2C
  scripts/config --disable CONFIG_BMP280_SPI
  scripts/config --disable CONFIG_IIO_CROS_EC_BARO
  scripts/config --disable CONFIG_DLHL60D
  scripts/config --disable CONFIG_DPS310
  scripts/config --disable CONFIG_HID_SENSOR_PRESS
  scripts/config --disable CONFIG_HP03
  scripts/config --disable CONFIG_ICP10100
  scripts/config --disable CONFIG_MPL115
  scripts/config --disable CONFIG_MPL115_I2C
  scripts/config --disable CONFIG_MPL115_SPI
  scripts/config --disable CONFIG_MPL3115
  scripts/config --disable CONFIG_MS5611
  scripts/config --disable CONFIG_MS5611_I2C
  scripts/config --disable CONFIG_MS5611_SPI
  scripts/config --disable CONFIG_MS5637
  scripts/config --disable CONFIG_IIO_ST_PRESS
  scripts/config --disable CONFIG_IIO_ST_PRESS_I2C
  scripts/config --disable CONFIG_IIO_ST_PRESS_SPI
  scripts/config --disable CONFIG_T5403
  scripts/config --disable CONFIG_HP206C
  scripts/config --disable CONFIG_ZPA2326
  scripts/config --disable CONFIG_ZPA2326_I2C
  scripts/config --disable CONFIG_ZPA2326_SPI
  # Proximity
  echo "Disable Proximity drivers"
  scripts/config --disable CONFIG_AS3935
  scripts/config --disable CONFIG_ISL29501
  scripts/config --disable CONFIG_LIDAR_LITE_V2
  scripts/config --disable CONFIG_MB1232
  scripts/config --disable CONFIG_PING
  scripts/config --disable CONFIG_RFD77402
  scripts/config --disable CONFIG_SRF04
  scripts/config --disable CONFIG_SX9310
  scripts/config --disable CONFIG_SX9500
  scripts/config --disable CONFIG_SRF08
  scripts/config --disable CONFIG_VCNL3020
  scripts/config --disable CONFIG_VL53L0X_I2C
  # Resolver
  echo "Disable Resolver drivers"
  scripts/config --disable CONFIG_AD2S90
  scripts/config --disable CONFIG_AD2S1200
  # Temperature
  echo "Disable Temperature"
  scripts/config --disable CONFIG_IQS620AT_TEMP
  scripts/config --disable CONFIG_LTC2983
  scripts/config --disable CONFIG_MAXIM_THERMOCOUPLE
  scripts/config --disable CONFIG_HID_SENSOR_TEMP
  scripts/config --disable CONFIG_MLX90614
  scripts/config --disable CONFIG_MLX90632
  scripts/config --disable CONFIG_TMP006
  scripts/config --disable CONFIG_TMP007
  scripts/config --disable CONFIG_TSYS01
  scripts/config --disable CONFIG_TSYS02D
  scripts/config --disable CONFIG_MAX31856
  # Trigger
  echo "Disable Trigger drivers"
  scripts/config --disable CONFIG_IIO_HRTIMER_TRIGGER
  scripts/config --disable CONFIG_IIO_INTERRUPT_TRIGGER
  scripts/config --disable CONFIG_IIO_STM32_LPTIMER_TRIGGER
  scripts/config --disable CONFIG_IIO_STM32_TIMER_TRIGGER
  scripts/config --disable CONFIG_IIO_TIGHTLOOP_TRIGGER
  scripts/config --disable CONFIG_IIO_SYSFS_TRIGGER

#######################################

  sleep 2s

############ Drivers/platform ############

  # Disable some platform drivers
  msg2 "Disable some platform drivers"
  # Chrome
  echo "Disable ChromOS dirvers"
  scripts/config --disable CONFIG_WILCO_EC
  scripts/config --disable CONFIG_WILCO_EC_DEBUGFS
  scripts/config --disable CONFIG_WILCO_EC_EVENTS
  scripts/config --disable CONFIG_WILCO_EC_TELEMETRY
  scripts/config --disable CONFIG_CHROME_PLATFORMS
  scripts/config --disable CONFIG_CHROMEOS_LAPTOP
  scripts/config --disable CONFIG_CHROMEOS_PSTORE
  scripts/config --disable CONFIG_CHROMEOS_TBMC
  scripts/config --disable CONFIG_CROS_EC
  scripts/config --disable CONFIG_CROS_EC_I2C
  scripts/config --disable CONFIG_CROS_EC_RPMSG
  scripts/config --disable CONFIG_CROS_EC_ISHTP
  scripts/config --disable CONFIG_CROS_EC_SPI
  scripts/config --disable CONFIG_CROS_EC_LPC
  scripts/config --disable CONFIG_CROS_EC_PROTO
  scripts/config --disable CONFIG_CROS_KBD_LED_BACKLIGHT
  scripts/config --disable CONFIG_CROS_EC_CHARDEV
  scripts/config --disable CONFIG_CROS_EC_LIGHTBAR
  scripts/config --disable CONFIG_CROS_EC_VBC
  scripts/config --disable CONFIG_CROS_EC_DEBUGFS
  scripts/config --disable CONFIG_CROS_EC_SENSORHUB
  scripts/config --disable CONFIG_CROS_EC_SYSFS
  scripts/config --disable CONFIG_CROS_EC_TYPEC
  scripts/config --disable CONFIG_CROS_USBPD_LOGGER
  scripts/config --disable CONFIG_CROS_USBPD_NOTIFY
  # Goldfish
  echo "Disable Goldfish drivers"
  scripts/config --disable CONFIG_GOLDFISH
  scripts/config --disable CONFIG_GOLDFISH_PIPE
  # Mellanox
  echo "Disable Mellanox drivers"
  scripts/config --disable CONFIG_MELLANOX_PLATFORM
  scripts/config --disable CONFIG_MLXREG_HOTPLUG
  scripts/config --disable CONFIG_MLXREG_IO
  scripts/config --disable CONFIG_MLXBF_TMFIFO
  scripts/config --disable CONFIG_MLXBF_BOOTCTL
  scripts/config --disable CONFIG_MLXBF_PMC
  # Mips
  echo "Disable Mips drivers"
  scripts/config --disable CONFIG_MIPS_PLATFORM_DEVICES
  scripts/config --disable CONFIG_CPU_HWMON
  scripts/config --disable CONFIG_RS780E_ACPI
  # Olpc
  echo "Disable Olpc drivers"
  scripts/config --disable CONFIG_OLPC_EC
  scripts/config --disable CONFIG_OLPC_XO175
  scripts/config --disable CONFIG_OLPC_XO175_EC
  # Surface
  echo "Disable Surface drivers"
  scripts/config --disable CONFIG_SURFACE_PLATFORMS
  scripts/config --disable CONFIG_SURFACE3_WMI
  scripts/config --disable CONFIG_SURFACE_3_BUTTON
  scripts/config --disable CONFIG_SURFACE_3_POWER_OPREGION
  scripts/config --disable CONFIG_SURFACE_GPE
  scripts/config --disable CONFIG_SURFACE_PRO3_BUTTON

  sleep 2s

  # Enable full support for x86 platform
  msg2 "Enable full support for x86 platform"
  scripts/config --enable CONFIG_X86_PLATFORM_DEVICES
  scripts/config --module CONFIG_ACPI_WMI
  scripts/config --module CONFIG_WMI_BMOF
  scripts/config --module CONFIG_ALIENWARE_WMI
  scripts/config --module CONFIG_HUAWEI_WMI
  scripts/config --module CONFIG_UV_SYSFS
  scripts/config --module CONFIG_INTEL_WMI_SBL_FW_UPDATE
  scripts/config --module CONFIG_INTEL_WMI_THUNDERBOLT
  scripts/config --module CONFIG_MXM_WMI
  scripts/config --module CONFIG_PEAQ_WMI
  scripts/config --module CONFIG_XIAOMI_WMI
  scripts/config --module CONFIG_ACERHDF
  scripts/config --module CONFIG_ACER_WIRELESS
  scripts/config --module CONFIG_ACER_WMI
  scripts/config --module CONFIG_AMD_PMC
  scripts/config --module CONFIG_ASUS_LAPTOP
  scripts/config --module CONFIG_ASUS_WIRELESS
  scripts/config --module CONFIG_ASUS_WMI
  scripts/config --module CONFIG_ASUS_NB_WMI
  scripts/config --module CONFIG_EEEPC_LAPTOP
  scripts/config --module CONFIG_EEEPC_WMI
  scripts/config --module CONFIG_DCDBAS
  scripts/config --module CONFIG_DELL_SMBIOS
  scripts/config --enable CONFIG_DELL_SMBIOS_WMI
  scripts/config --enable CONFIG_DELL_SMBIOS_SMM
  scripts/config --module CONFIG_DELL_LAPTOP
  scripts/config --module CONFIG_DELL_RBTN
  scripts/config --module CONFIG_DELL_RBU
  scripts/config --module CONFIG_DELL_SMO8800
  scripts/config --module CONFIG_DELL_WMI
  scripts/config --module CONFIG_DELL_WMI_SYSMAN
  scripts/config --module CONFIG_DELL_WMI_DESCRIPTOR
  scripts/config --module CONFIG_DELL_WMI_AIO
  scripts/config --module CONFIG_DELL_WMI_LED
  scripts/config --module CONFIG_AMILO_RFKILL
  scripts/config --module CONFIG_FUJITSU_LAPTOP
  scripts/config --module CONFIG_FUJITSU_TABLET
  scripts/config --module CONFIG_GPD_POCKET_FAN
  scripts/config --module CONFIG_HP_ACCEL
  scripts/config --module CONFIG_HP_WIRELESS
  scripts/config --module CONFIG_HP_WMI
  scripts/config --module CONFIG_TC1100_WMI
  scripts/config --module CONFIG_IBM_RTL
  scripts/config --module CONFIG_IDEAPAD_LAPTOP
  scripts/config --module CONFIG_SENSORS_HDAPS
  scripts/config --module CONFIG_THINKPAD_ACPI
  scripts/config --enable CONFIG_THINKPAD_ACPI_ALSA_SUPPORT
  scripts/config --enable CONFIG_THINKPAD_ACPI_VIDEO
  scripts/config --enable CONFIG_THINKPAD_ACPI_HOTKEY_POLL
  scripts/config --module CONFIG_INTEL_ATOMISP2_LED
  scripts/config --module CONFIG_INTEL_ATOMISP2_PM
  scripts/config --module CONFIG_INTEL_CHT_INT33FE
  scripts/config --module CONFIG_INTEL_HID_EVENT
  scripts/config --module CONFIG_INTEL_INT0002_VGPIO
  scripts/config --module CONFIG_INTEL_MENLOW
  scripts/config --module CONFIG_INTEL_OAKTRAIL
  scripts/config --module CONFIG_MSI_LAPTOP
  scripts/config --module CONFIG_MSI_WMI
  scripts/config --module CONFIG_XO15_EBOOK
  scripts/config --module CONFIG_XO1_RFKILL
  scripts/config --module CONFIG_PCENGINES_APU2
  scripts/config --module CONFIG_SAMSUNG_LAPTOP
  scripts/config --module CONFIG_SAMSUNG_Q10
  scripts/config --module CONFIG_ACPI_TOSHIBA
  scripts/config --module CONFIG_TOSHIBA_BT_RFKILL
  scripts/config --module CONFIG_TOSHIBA_HAPS
  scripts/config --module CONFIG_TOSHIBA_WMI
  scripts/config --module CONFIG_ACPI_CMPC
  scripts/config --module CONFIG_LG_LAPTOP
  scripts/config --module CONFIG_PANASONIC_LAPTOP
  scripts/config --module CONFIG_SONY_LAPTOP
  scripts/config --enable CONFIG_SONYPI_COMPAT
  scripts/config --module CONFIG_SYSTEM76_ACPI
  scripts/config --module CONFIG_TOPSTAR_LAPTOP
  scripts/config --module CONFIG_I2C_MULTI_INSTANTIATE
  scripts/config --module CONFIG_MLX_PLATFORM
  scripts/config --enable CONFIG_TOUCHSCREEN_DMI
  scripts/config --enable CONFIG_INTEL_IMR
  scripts/config --module CONFIG_INTEL_IPS
  scripts/config --module CONFIG_INTEL_RST
  scripts/config --module CONFIG_INTEL_SMARTCONNECT
  scripts/config --enable CONFIG_INTEL_TURBO_MAX_3
  scripts/config --module CONFIG_INTEL_UNCORE_FREQ_CONTROL
  scripts/config --module CONFIG_INTEL_BXTWC_PMIC_TMU
  scripts/config --module CONFIG_INTEL_CHTDC_TI_PWRBTN
  scripts/config --module CONFIG_INTEL_MFLD_THERMAL
  scripts/config --module CONFIG_INTEL_MID_POWER_BUTTON
  scripts/config --module CONFIG_INTEL_MRFLD_PWRBTN
  scripts/config --enable CONFIG_INTEL_PMC_CORE
  scripts/config --module CONFIG_INTEL_PMT_CLASS
  scripts/config --module CONFIG_INTEL_PMT_TELEMETRY
  scripts/config --module CONFIG_INTEL_PMT_CRASHLOG
  scripts/config --module CONFIG_INTEL_PUNIT_IPC
  scripts/config --enable CONFIG_INTEL_SCU_IPC
  scripts/config --enable CONFIG_INTEL_SCU
  scripts/config --enable CONFIG_INTEL_SCU_PCI
  scripts/config --module CONFIG_INTEL_SCU_PLATFORM
  scripts/config --module CONFIG_INTEL_SCU_IPC_UTIL
  scripts/config --module CONFIG_INTEL_TELEMETRY
  scripts/config --enable CONFIG_PMC_ATOM

#######################################

  sleep 2s

############ Net/ipv6 ############

  # Disable Ipv6
  msg2 "Disable Ipv6 ... Everybody use Ipv4"
  scripts/config --disable CONFIG_IPV6
  scripts/config --disable CONFIG_IPV6_ROUTER_PREF
  scripts/config --disable CONFIG_IPV6_ROUTE_INFO
  scripts/config --disable CONFIG_IPV6_OPTIMISTIC_DAD
  scripts/config --disable CONFIG_INET6_AH
  scripts/config --disable CONFIG_INET6_ESP
  scripts/config --disable CONFIG_INET6_ESP_OFFLOAD
  scripts/config --disable CONFIG_INET6_ESPINTCP
  scripts/config --disable CONFIG_INET6_IPCOMP
  scripts/config --disable CONFIG_IPV6_MIP6
  scripts/config --disable CONFIG_IPV6_ILA
  scripts/config --disable CONFIG_INET6_XFRM_TUNNEL
  scripts/config --disable CONFIG_INET6_TUNNEL
  scripts/config --disable CONFIG_IPV6_VTI
  scripts/config --disable CONFIG_IPV6_SIT
  scripts/config --disable CONFIG_IPV6_SIT_6RD
  scripts/config --disable CONFIG_IPV6_NDISC_NODETYPE
  scripts/config --disable CONFIG_IPV6_TUNNEL
  scripts/config --disable CONFIG_IPV6_GRE
  scripts/config --disable CONFIG_IPV6_FOU
  scripts/config --disable CONFIG_IPV6_FOU_TUNNEL
  scripts/config --disable CONFIG_IPV6_MULTIPLE_TABLES
  scripts/config --disable CONFIG_IPV6_SUBTREES
  scripts/config --disable CONFIG_IPV6_MROUTE
  scripts/config --disable CONFIG_IPV6_MROUTE_MULTIPLE_TABLES
  scripts/config --disable CONFIG_IPV6_PIMSM_V2
  scripts/config --disable CONFIG_IPV6_SEG6_LWTUNNEL
  scripts/config --disable CONFIG_IPV6_SEG6_HMAC
  scripts/config --disable CONFIG_IPV6_SEG6_BPF
  scripts/config --disable CONFIG_IPV6_RPL_LWTUNNEL
  scripts/config --disable CONFIG_NF_SOCKET_IPV6
  scripts/config --disable CONFIG_NF_TPROXY_IPV6
  scripts/config --disable CONFIG_NF_TABLES_IPV6
  scripts/config --disable CONFIG_NFT_REJECT_IPV6
  scripts/config --disable CONFIG_NFT_DUP_IPV6
  scripts/config --disable CONFIG_NFT_FIB_IPV6
  scripts/config --disable CONFIG_NF_FLOW_TABLE_IPV6
  scripts/config --disable CONFIG_NF_DUP_IPV6
  scripts/config --disable CONFIG_NF_REJECT_IPV6
  scripts/config --disable CONFIG_NF_LOG_IPV6
  scripts/config --disable CONFIG_IP6_NF_IPTABLES
  scripts/config --disable CONFIG_IP6_NF_IPTABLES
  scripts/config --disable CONFIG_IP6_NF_MATCH_AH
  scripts/config --disable CONFIG_IP6_NF_MATCH_EUI64
  scripts/config --disable CONFIG_IP6_NF_MATCH_FRAG
  scripts/config --disable CONFIG_IP6_NF_MATCH_OPTS
  scripts/config --disable CONFIG_IP6_NF_MATCH_HL
  scripts/config --disable CONFIG_IP6_NF_MATCH_IPV6HEADER
  scripts/config --disable CONFIG_IP6_NF_MATCH_MH
  scripts/config --disable CONFIG_IP6_NF_MATCH_RPFILTER
  scripts/config --disable CONFIG_IP6_NF_MATCH_RT
  scripts/config --disable CONFIG_IP6_NF_MATCH_SRH
  scripts/config --disable CONFIG_IP6_NF_TARGET_HL
  scripts/config --disable CONFIG_IP6_NF_FILTER
  scripts/config --disable CONFIG_IP6_NF_TARGET_REJECT
  scripts/config --disable CONFIG_IP6_NF_TARGET_SYNPROXY
  scripts/config --disable CONFIG_IP6_NF_MANGLE
  scripts/config --disable CONFIG_IP6_NF_RAW
  scripts/config --disable CONFIG_IP6_NF_SECURITY
  scripts/config --disable CONFIG_IP6_NF_NAT
  scripts/config --disable CONFIG_IP6_NF_TARGET_MASQUERADE
  scripts/config --disable CONFIG_IP6_NF_TARGET_NPT
  scripts/config --disable CONFIG_NF_DEFRAG_IPV6

#######################################

  sleep 2s

############ Drivers/Gnss ############

  # Disable Gnss drivers
  msg2 "Disable Gnss drivers"
  scripts/config --disable CONFIG_GNSS
  scripts/config --disable CONFIG_GNSS_SERIAL
  scripts/config --disable CONFIG_GNSS_SIRF_SERIAL
  scripts/config --disable CONFIG_GNSS_UBX_SERIAL

#######################################

  sleep 2s

############ Debugs ############

  # Disable CONFIG_DEBUG_INFO=y at build time otherwise memory usage blows up
  # and can easily overwhelm a system with 32 GB of memory using a tmpfs build
  # "partition ... this was introduced by FS#66260, see
  # "https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=663b08666b269eeeeaafbafaee07fd03389ac8d7
  msg2 "Disable debbug options"
  scripts/config --disable CONFIG_SLUB_DEBUG
  scripts/config --disable CONFIG_PM_DEBUG
  scripts/config --disable CONFIG_PM_ADVANCED_DEBUG
  scripts/config --disable CONFIG_PM_SLEEP_DEBUG
  scripts/config --disable CONFIG_ACPI_DEBUG
  scripts/config --disable CONFIG_SCHED_DEBUG
  scripts/config --disable CONFIG_LATENCYTOP
  scripts/config --disable CONFIG_DEBUG_PREEMPT
  scripts/config --disable CONFIG_DEBUG_INFO
  scripts/config --disable CONFIG_CGROUP_BPF
  scripts/config --disable CONFIG_BPF_LSM
  scripts/config --disable CONFIG_BPF_PRELOAD
  scripts/config --disable CONFIG_BPF_LIRC_MODE2
  scripts/config --disable CONFIG_BPF_KPROBE_OVERRIDE
  scripts/config --disable CONFIG_DEBUG_INFO_REDUCED
  scripts/config --disable CONFIG_DEBUG_INFO_COMPRESSED
  scripts/config --disable CONFIG_DEBUG_INFO_SPLI
  scripts/config --disable CONFIG_GDB_SCRIPTS
  scripts/config --disable CONFIG_DEBUG_INFO_DWARF4
  scripts/config --disable CONFIG_DEBUG_INFO_BTF
  scripts/config --disable CONFIG_BPF_PRELOAD
  scripts/config --disable CONFIG_BPF_PRELOAD_UMD
  scripts/config --disable CONFIG_BPF_STREAM_PARSER
  scripts/config --disable CONFIG_DMA_API_DEBUG
  scripts/config --disable CONFIG_DMA_API_DEBUG_SG
  scripts/config --disable CONFIG_DMA_MAP_BENCHMARK
  scripts/config --disable CONFIG_DEBUG_FS
  scripts/config --disable CONFIG_GCOV_KERNEL
  scripts/config --disable CONFIG_GCOV_PROFILE_ALL
  scripts/config --disable CONFIG_DEBUG_FS
  scripts/config --disable CONFIG_GENERIC_IRQ_DEBUGFS
  scripts/config --disable CONFIG_ACPI_DEBUGGER
  scripts/config --disable CONFIG_ACPI_DEBUGGER_USER
  scripts/config --disable CONFIG_ACPI_EC_DEBUGFS
  scripts/config --disable CONFIG_ACPI_APEI_ERST_DEBUG
  scripts/config --disable CONFIG_NFIT_SECURITY_DEBUG
  scripts/config --disable CONFIG_DMADEVICES_DEBUG
  scripts/config --disable CONFIG_DMADEVICES_VDEBUG
  scripts/config --disable CONFIG_DMATEST
  scripts/config --disable CONFIG_BTRFS_DEBUG
  scripts/config --disable CONFIG_BTRFS_FS_REF_VERIFY
  scripts/config --disable CONFIG_BTRFS_ASSERT
  scripts/config --disable CONFIG_BTRFS_FS_RUN_SANITY_TESTS
  scripts/config --disable CONFIG_BTRFS_FS_CHECK_INTEGRITY
  scripts/config --disable CONFIG_EXT4_DEBUG
  scripts/config --disable CONFIG_EXT4_KUNIT_TESTS
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG_ASSERTS
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG_MESSAGES
  scripts/config --disable CONFIG_SECURITY_APPARMOR_KUNIT_TEST
  scripts/config --disable CONFIG_POWER_SUPPLY_DEBUG
  scripts/config --disable CONFIG_NTFS_DEBUG
  scripts/config --disable CONFIG_GENERIC_IRQ_DEBUGFS
  scripts/config --disable CONFIG_CIFS_STATS2
  scripts/config --disable CONFIG_CIFS_DEBUG
  scripts/config --disable CONFIG_CIFS_DEBUG2
  scripts/config --disable CONFIG_CIFS_DEBUG_DUMP_KEYS
  scripts/config --disable CONFIG_JBD2_DEBUG
  scripts/config --disable CONFIG_CONFIG_NFS_DEBUG
  scripts/config --disable CONFIG_TRACE_IRQFLAGS_SUPPORT
  scripts/config --disable CONFIG_TRACE_IRQFLAGS_NMI_SUPPORT
  scripts/config --disable CONFIG_EARLY_PRINTK_USB
  scripts/config --disable CONFIG_X86_VERBOSE_BOOTUP
  scripts/config --disable CONFIG_EARLY_PRINTK
  scripts/config --disable CONFIG_EARLY_PRINTK_DBGP
  scripts/config --disable CONFIG_EARLY_PRINTK_USB_XDBC
  scripts/config --disable CONFIG_EFI_PGT_DUMP
  scripts/config --disable CONFIG_DEBUG_TLBFLUSH
  scripts/config --disable CONFIG_IOMMU_DEBUG
  scripts/config --disable CONFIG_IOMMU_LEAK
  scripts/config --disable CONFIG_HAVE_MMIOTRACE_SUPPORT
  scripts/config --disable CONFIG_X86_DECODER_SELFTEST
  scripts/config --disable CONFIG_IO_DELAY_0X80
  scripts/config --disable CONFIG_IO_DELAY_0XED
  scripts/config --disable CONFIG_IO_DELAY_UDELAY
  scripts/config --disable CONFIG_IO_DELAY_NONE
  scripts/config --disable CONFIG_DEBUG_BOOT_PARAMS
  scripts/config --disable CONFIG_CPA_DEBUG
  scripts/config --disable CONFIG_DEBUG_ENTRY
  scripts/config --disable CONFIG_DEBUG_NMI_SELFTEST
  scripts/config --disable CONFIG_DEBUG_IMR_SELFTEST
  scripts/config --disable CONFIG_X86_DEBUG_FPU
  scripts/config --disable CONFIG_PUNIT_ATOM_DEBUG
  scripts/config --disable CONFIG_UNWINDER_ORC
  scripts/config --disable CONFIG_UNWINDER_FRAME_POINTER
  scripts/config --disable CONFIG_UNWINDER_GUESS
  scripts/config --disable CONFIG_FRAME_POINTER
  scripts/config --disable CONFIG_THINKPAD_ACPI_DEBUGFACILITIES
  scripts/config --disable CONFIG_THINKPAD_ACPI_DEBUG
  scripts/config --disable CONFIG_THINKPAD_ACPI_UNSAFE_LEDS
  scripts/config --disable CONFIG_CMA_DEBUG
  scripts/config --disable CONFIG_CMA_DEBUGFS
  scripts/config --disable CONFIG_EDAC_DEBUG
  scripts/config --disable CONFIG_ATM_IA_DEBUG
  scripts/config --disable CONFIG_ATM_FORE200E_DEBUG
  scripts/config --disable CONFIG_BCMA_DEBUG

#######################################

  sleep 2s

  if [[ "$_cpu_sched" = "1" ]]; then
    # https://bbs.archlinux.org/viewtopic.php?pid=1824594#p1824594
    msg2 "Enable CONFIG_PSI_DEFAULT_DISABLED"
    scripts/config --enable CONFIG_PSI_DEFAULT_DISABLED
    # FS#66613
    # https://bugzilla.kernel.org/show_bug.cgi?id=207173#c6
    msg2 "Disable CONFIG_KVM_WERROR"
    scripts/config --disable CONFIG_KVM_WERROR

    sleep 2s
  fi
}
