#!/usr/bin/bash

rapid_config(){
  msg2 "Set SIG level to SHA512"
  scripts/config --undefine MODULE_SIG_FORCE
  scripts/config --disable MODULE_SIG_FORCE
  scripts/config --enable CONFIG_MODULE_SIG
  scripts/config --enable CONFIG_MODULE_SIG_ALL
  scripts/config --disable CONFIG_MODULE_SIG_SHA1
  scripts/config --disable CONFIG_MODULE_SIG_SHA224
  scripts/config --disable CONFIG_MODULE_SIG_SHA256
  scripts/config --disable CONFIG_MODULE_SIG_SHA384
  scripts/config --enable CONFIG_MODULE_SIG_SHA512
  scripts/config  --set-val CONFIG_MODULE_SIG_HASH "sha512"

  msg2 "Set module compression to ZSTD"
  scripts/config --enable CONFIG_MODULE_COMPRESS
  scripts/config --disable CONFIG_MODULE_COMPRESS_GZIP
  scripts/config --disable CONFIG_MODULE_COMPRESS_XZ
  scripts/config --enable CONFIG_MODULE_COMPRESS_ZSTD

  msg2 "Enable CONFIG_STACK_VALIDATION"
  scripts/config --enable CONFIG_STACK_VALIDATION

  msg2 "Enable IKCONFIG"
  scripts/config --enable CONFIG_IKCONFIG
  scripts/config --enable CONFIG_IKCONFIG_PROC

  msg2 "Disable NUMA"
  scripts/config --disable CONFIG_NUMA
  scripts/config --disable CONFIG_AMD_NUMA
  scripts/config --disable CONFIG_X86_64_ACPI_NUMA
  scripts/config --disable CONFIG_NODES_SPAN_OTHER_NODES
  scripts/config --disable CONFIG_NUMA_EMU
  scripts/config --disable CONFIG_NEED_MULTIPLE_NODES
  scripts/config --disable CONFIG_USE_PERCPU_NUMA_NODE_ID
  scripts/config --disable CONFIG_ACPI_NUMA
  scripts/config --disable CONFIG_ARCH_SUPPORTS_NUMA_BALANCING
  scripts/config --disable CONFIG_NODES_SHIFT
  scripts/config --undefine CONFIG_NODES_SHIFT
  scripts/config --disable CONFIG_NEED_MULTIPLE_NODES

  msg2 "Disable FUNCTION_TRACER/GRAPH_TRACER"
  scripts/config --disable CONFIG_FUNCTION_TRACER
  scripts/config --disable CONFIG_STACK_TRACER

  msg2 "Disable CONFIG_USER_NS_UNPRIVILEGED"
  scripts/config --disable CONFIG_USER_NS_UNPRIVILEGED

  scripts/config --disable CONFIG_CPU_FREQ_DEFAULT_GOV_POWERSAVE
  scripts/config --disable CONFIG_CPU_FREQ_GOV_POWERSAVE
  scripts/config --disable CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE
  scripts/config --disable CONFIG_CPU_FREQ_GOV_USERSPACE
  scripts/config --disable CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND
  scripts/config --disable CONFIG_CPU_FREQ_GOV_ONDEMAND
  scripts/config --disable CONFIG_CPU_FREQ_DEFAULT_GOV_CONSERVATIVE
  scripts/config --disable CONFIG_CPU_FREQ_GOV_CONSERVATIVE
  scripts/config --disable CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL
  scripts/config --disable CONFIG_CPU_FREQ_GOV_SCHEDUTIL
  scripts/config --enable CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE
  scripts/config --enable CONFIG_CPU_FREQ_GOV_PERFORMANCE

  msg2 "Set CPU DEVFREQ GOV CONFIG_DEVFREQ_GOV for performance"
  scripts/config --disable CONFIG_DEVFREQ_GOV_SIMPLE_ONDEMAND
  scripts/config --undefine CONFIG_DEVFREQ_GOV_SIMPLE_ONDEMAND
  scripts/config --disable CONFIG_DEVFREQ_GOV_POWERSAVE
  scripts/config --disable CONFIG_DEVFREQ_GOV_USERSPACE
  scripts/config --disable CONFIG_DEVFREQ_GOV_PASSIVE
  scripts/config --enable CONFIG_DEVFREQ_GOV_PERFORMANCE

  msg2 "Set PCIEASPM DRIVER to performance"
  scripts/config --enable CONFIG_PCIEASPM
  scripts/config --enable CONFIG_PCIEASPM_PERFORMANCE

  msg2 "Set CONFIG_PCIE_BUS for performance"
  scripts/config --enable CONFIG_PCIE_BUS_PERFORMANCE

  msg2 "Enable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3"
  scripts/config --disable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE
  scripts/config --disable CONFIG_CC_OPTIMIZE_FOR_SIZE
  scripts/config --enable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3

  msg2 "Set timer frequency to 1000HZ"
  scripts/config --enable CONFIG_HZ_1000
  scripts/config --set-val CONFIG_HZ 1000

  msg2 "Enable PREEMPT"
  scripts/config --disable CONFIG_PREEMPT_NONE
  scripts/config --disable CONFIG_PREEMPT_VOLUNTARY
  scripts/config --enable CONFIG_PREEMPT
  scripts/config --enable CONFIG_PREEMPT_COUNT
  scripts/config --enable CONFIG_PREEMPTION

  msg2 "Set to full tickless"
  scripts/config --disable CONFIG_HZ_PERIODIC
  scripts/config --disable CONFIG_NO_HZ_IDLE
  scripts/config --enable CONFIG_NO_HZ_FULL
  scripts/config --enable CONFIG_NO_HZ
  scripts/config --enable CONFIG_NO_HZ_COMMON
  #scripts/config --enable CONFIG_CONTEXT_TRACKING
  #scripts/config --disable CONFIG_CONTEXT_TRACKING_FORCE

  msg2 "Enable Device Tree and Open Firmware support"
  scripts/config --enable CONFIG_OF

  msg2 "Enable tristate V4L2 loopback device"
  scripts/config --module CONFIG_V4L2_LOOPBACK

  msg2 "Enable ntfs"
  scripts/config --module CONFIG_NTFS_FS
  scripts/config --enable CONFIG_NTFS_RW
  msg2 "Enable ntfs3"
  scripts/config --module CONFIG_NTFS3_FS
  scripts/config --enable CONFIG_NTFS3_64BIT_CLUSTER
  scripts/config --enable CONFIG_NTFS3_LZX_XPRESS
  scripts/config --enable CONFIG_NTFS3_FS_POSIX_ACL

  msg2 "Enable CONFIG_VHBA"
  scripts/config --module CONFIG_VHBA

  msg2 "Disabling Kyber I/O scheduler"
  scripts/config --disable CONFIG_MQ_IOSCHED_KYBER

  msg2 "Enable Deadline I/O scheduler"
  scripts/config --enable CONFIG_MQ_IOSCHED_DEADLINE

  msg2 "Enable MQ-Deadline-Nodefault I/O scheduler"
  scripts/config --enable CONFIG_MQ_IOSCHED_DEADLINE_NODEFAULT

  msg2 "Enable CONFIG_BFQ_CGROUP_DEBUG..."
  scripts/config --enable CONFIG_BFQ_CGROUP_DEBUG

  msg2 "Disable debug options"
  scripts/config --disable CONFIG_SLUB_DEBUG
  scripts/config --disable CONFIG_PM_DEBUG
  scripts/config --disable CONFIG_PM_ADVANCED_DEBUG
  scripts/config --disable CONFIG_PM_SLEEP_DEBUG
  scripts/config --disable CONFIG_ACPI_DEBUG
  scripts/config --disable CONFIG_SCHED_DEBUG
  scripts/config --disable CONFIG_LATENCYTOP
  scripts/config --disable CONFIG_DEBUG_PREEMPT
  scripts/config --disable CONFIG_DEBUG_INFO
  scripts/config --disable CONFIG_CGROUP_BPF
  scripts/config --disable CONFIG_BPF_LSM
  scripts/config --disable CONFIG_BPF_PRELOAD
  scripts/config --disable CONFIG_BPF_LIRC_MODE2
  scripts/config --disable CONFIG_BPF_KPROBE_OVERRIDE
  scripts/config --disable CONFIG_DEBUG_INFO_REDUCED
  scripts/config --disable CONFIG_DEBUG_INFO_COMPRESSED
  scripts/config --disable CONFIG_DEBUG_INFO_SPLI
  scripts/config --disable CONFIG_GDB_SCRIPTS
  scripts/config --disable CONFIG_DEBUG_INFO_DWARF4
  scripts/config --disable CONFIG_DEBUG_INFO_BTF
  scripts/config --disable CONFIG_BPF_PRELOAD
  scripts/config --disable CONFIG_BPF_PRELOAD_UMD
  scripts/config --disable CONFIG_BPF_STREAM_PARSER
  scripts/config --disable CONFIG_DMA_API_DEBUG
  scripts/config --disable CONFIG_DMA_API_DEBUG_SG
  scripts/config --disable CONFIG_DMA_MAP_BENCHMARK
  scripts/config --disable CONFIG_DEBUG_FS
  scripts/config --disable CONFIG_GCOV_KERNEL
  scripts/config --disable CONFIG_GCOV_PROFILE_ALL
  scripts/config --disable CONFIG_DEBUG_FS
  scripts/config --disable CONFIG_GENERIC_IRQ_DEBUGFS
  scripts/config --disable CONFIG_ACPI_DEBUGGER
  scripts/config --disable CONFIG_ACPI_DEBUGGER_USER
  scripts/config --disable CONFIG_ACPI_EC_DEBUGFS
  scripts/config --disable CONFIG_ACPI_APEI_ERST_DEBUG
  scripts/config --disable CONFIG_NFIT_SECURITY_DEBUG
  scripts/config --disable CONFIG_DMADEVICES_DEBUG
  scripts/config --disable CONFIG_DMADEVICES_VDEBUG
  scripts/config --disable CONFIG_DMATEST
  scripts/config --disable CONFIG_BTRFS_DEBUG
  scripts/config --disable CONFIG_BTRFS_FS_REF_VERIFY
  scripts/config --disable CONFIG_BTRFS_ASSERT
  scripts/config --disable CONFIG_BTRFS_FS_RUN_SANITY_TESTS
  scripts/config --disable CONFIG_BTRFS_FS_CHECK_INTEGRITY
  scripts/config --disable CONFIG_EXT4_DEBUG
  scripts/config --disable CONFIG_EXT4_KUNIT_TESTS
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG_ASSERTS
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG_MESSAGES
  scripts/config --disable CONFIG_SECURITY_APPARMOR_KUNIT_TEST
  scripts/config --disable CONFIG_POWER_SUPPLY_DEBUG
  scripts/config --disable CONFIG_NTFS_DEBUG
  scripts/config --disable CONFIG_GENERIC_IRQ_DEBUGFS
  scripts/config --disable CONFIG_CIFS_STATS2
  scripts/config --disable CONFIG_CIFS_DEBUG
  scripts/config --disable CONFIG_CIFS_DEBUG2
  scripts/config --disable CONFIG_CIFS_DEBUG_DUMP_KEYS
  scripts/config --disable CONFIG_JBD2_DEBUG
  scripts/config --disable CONFIG_CONFIG_NFS_DEBUG
  scripts/config --disable CONFIG_TRACE_IRQFLAGS_SUPPORT
  scripts/config --disable CONFIG_TRACE_IRQFLAGS_NMI_SUPPORT
  scripts/config --disable CONFIG_EARLY_PRINTK_USB
  scripts/config --disable CONFIG_X86_VERBOSE_BOOTUP
  scripts/config --disable CONFIG_EARLY_PRINTK
  scripts/config --disable CONFIG_EARLY_PRINTK_DBGP
  scripts/config --disable CONFIG_EARLY_PRINTK_USB_XDBC
  scripts/config --disable CONFIG_EFI_PGT_DUMP
  scripts/config --disable CONFIG_DEBUG_TLBFLUSH
  scripts/config --disable CONFIG_IOMMU_DEBUG
  scripts/config --disable CONFIG_IOMMU_LEAK
  scripts/config --disable CONFIG_HAVE_MMIOTRACE_SUPPORT
  scripts/config --disable CONFIG_X86_DECODER_SELFTEST
  scripts/config --disable CONFIG_IO_DELAY_0X80
  scripts/config --disable CONFIG_IO_DELAY_0XED
  scripts/config --disable CONFIG_IO_DELAY_UDELAY
  scripts/config --disable CONFIG_IO_DELAY_NONE
  scripts/config --disable CONFIG_DEBUG_BOOT_PARAMS
  scripts/config --disable CONFIG_CPA_DEBUG
  scripts/config --disable CONFIG_DEBUG_ENTRY
  scripts/config --disable CONFIG_DEBUG_NMI_SELFTEST
  scripts/config --disable CONFIG_DEBUG_IMR_SELFTEST
  scripts/config --disable CONFIG_X86_DEBUG_FPU
  scripts/config --disable CONFIG_PUNIT_ATOM_DEBUG
  scripts/config --disable CONFIG_UNWINDER_ORC
  scripts/config --disable CONFIG_UNWINDER_FRAME_POINTER
  scripts/config --disable CONFIG_UNWINDER_GUESS
  scripts/config --disable CONFIG_FRAME_POINTER
  scripts/config --disable CONFIG_THINKPAD_ACPI_DEBUGFACILITIES
  scripts/config --disable CONFIG_THINKPAD_ACPI_DEBUG
  scripts/config --disable CONFIG_THINKPAD_ACPI_UNSAFE_LEDS
  scripts/config --disable CONFIG_CMA_DEBUG
  scripts/config --disable CONFIG_CMA_DEBUGFS
  scripts/config --disable CONFIG_EDAC_DEBUG
  scripts/config --disable CONFIG_ATM_IA_DEBUG
  scripts/config --disable CONFIG_ATM_FORE200E_DEBUG
  scripts/config --disable CONFIG_BCMA_DEBUG

  msg2 "Enable CONFIG_SCHED_AUTOGROUP_DEFAULT_ENABLED"
  scripts/config --enable CONFIG_SCHED_AUTOGROUP_DEFAULT_ENABLED

  msg2 "Enable CONFIG_ZENIFY"
  scripts/config --enable CONFIG_ZENIFY

  msg2 "Enable Fsync support"
  scripts/config --enable CONFIG_FUTEX
  scripts/config --enable CONFIG_FUTEX_PI

  msg2 "Enable Futex2 support"
  scripts/config --enable CONFIG_FUTEX2

  msg2 "Enable winesync support"
  scripts/config --module CONFIG_WINESYNC

  if [[ $_cpu_sched = "1" ]]; then
    msg2 "Enable MuQSS"
    scripts/config --enable CONFIG_SCHED_MC
    scripts/config --enable CONFIG_SCHED_SMT
    scripts/config --enable CONFIG_SMP
    scripts/config --enable CONFIG_SCHED_MC_PRIO
    scripts/config --enable CONFIG_SCHED_MUQSS
    msg2 "Disable CFS"
    scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    scripts/config --disable CONFIG_CFS_BANDWIDTH
    msg2 "Set to RQ_MC"
    scripts/config --enable CONFIG_RQ_MC
    scripts/config --set-val CONFIG_SHARERQ 2
    msg2 "Disable CFS"
    scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    scripts/config --disable CONFIG_CFS_BANDWIDTH
  elif [[ $_cpu_sched = "2" ]]; then
    msg2 "Enable CONFIG_SCHED_ALT, this feature enable alternative CPU scheduler..."
    scripts/config --enable CONFIG_SCHED_ALT
    msg2 "Enable BMQ CPU scheduler..."
    scripts/config --enable CONFIG_SCHED_BMQ
    scripts/config --disable CONFIG_SCHED_PDS
    msg2 "Disable CFS"
    scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    scripts/config --disable CONFIG_CFS_BANDWIDTH
  elif [[ $_cpu_sched = "3" ]]; then
    msg2 "Enable CONFIG_SCHED_ALT, this feature enable alternative CPU scheduler..."
    scripts/config --enable CONFIG_SCHED_ALT
    msg2 "Enable PDS CPU scheduler..."
    scripts/config --disable CONFIG_SCHED_BMQ
    scripts/config --enable CONFIG_SCHED_PDS
    msg2 "Disable CFS"
    scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    scripts/config --disable CONFIG_CFS_BANDWIDTH
  elif [[ $_cpu_sched = "4" ]]; then
    msg2 "Enable CacULE CPU scheduler..."
    scripts/config --enable CONFIG_CACULE_SCHED
    msg2 "Disable CFS"
    scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    scripts/config --disable CONFIG_CFS_BANDWIDTH
  elif [[ $_cpu_sched = "5" ]]; then
    msg2 "Enable CONFIG_SCHED_ALT, this feature enable alternative CPU scheduler..."
    scripts/config --enable CONFIG_SCHED_ALT
    msg2 "Enable UPDS CPU scheduler..."
    scripts/config --disable CONFIG_SCHED_BMQ
    scripts/config --enable CONFIG_SCHED_PDS
    msg2 "Disable CFS"
    scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    scripts/config --disable CONFIG_CFS_BANDWIDTH
  elif [[ $_cpu_sched = "6" ]]; then
    msg2 "Enable CacULE CPU scheduler..."
    scripts/config --enable CONFIG_CACULE_SCHED
    msg2 "Enable CacULE-RDB CPU scheduler..."
    scripts/config --enable CONFIG_CACULE_RDB
    msg2 "Disable CFS"
    scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    scripts/config --disable CONFIG_CFS_BANDWIDTH
  else
    msg2 "Enable CFS"
    scripts/config --enable CONFIG_FAIR_GROUP_SCHED
    scripts/config --enable CONFIG_CFS_BANDWIDTH
  fi

  msg2 "Set CONFIG_GENERIC_CPU"
  scripts/config --enable CONFIG_GENERIC_CPU
}
